import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1766732359883 implements MigrationInterface {
    name = 'InitialSchema1766732359883'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."traffic_events_source_enum" AS ENUM('google', 'facebook', 'instagram', 'whatsapp', 'tiktok', 'twitter', 'snapchat', 'bing', 'youtube', 'chatgpt', 'claude', 'gemini', 'grok', 'direct', 'other')`);
        await queryRunner.query(`CREATE TABLE "traffic_events" ("id" SERIAL NOT NULL, "businessId" integer NOT NULL, "referralUrl" character varying, "landingPage" character varying, "source" "public"."traffic_events_source_enum" NOT NULL DEFAULT 'direct', "ipAddress" character varying, "userAgent" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_87a65c9bea945143ca44e218fe3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_TRAFFIC_BUSINESS_SOURCE" ON "traffic_events" ("businessId", "source") `);
        await queryRunner.query(`CREATE INDEX "IDX_TRAFFIC_BUSINESS_CREATED" ON "traffic_events" ("businessId", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_TRAFFIC_CREATED_AT" ON "traffic_events" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_TRAFFIC_BUSINESS_ID" ON "traffic_events" ("businessId") `);
        await queryRunner.query(`CREATE TABLE "business_types" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_3894005288e759379ee7b56622a" UNIQUE ("name"), CONSTRAINT "PK_3c34c2b0b96fd7d13d7b4750b27" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."roles_usertype_enum" AS ENUM('user', 'admin', 'super_admin')`);
        await queryRunner.query(`CREATE TYPE "public"."roles_status_enum" AS ENUM('active', 'inactive', 'suspended')`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "description" character varying, "userType" "public"."roles_usertype_enum" NOT NULL, "permissions" text, "status" "public"."roles_status_enum" NOT NULL DEFAULT 'active', "isSystemRole" boolean NOT NULL DEFAULT false, "priority" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" integer, "updatedBy" integer, CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id")); COMMENT ON COLUMN "roles"."userType" IS 'Determines if this role is for users or administrative staff'; COMMENT ON COLUMN "roles"."permissions" IS 'Array of permission strings'; COMMENT ON COLUMN "roles"."isSystemRole" IS 'System roles cannot be deleted'; COMMENT ON COLUMN "roles"."priority" IS 'Higher priority = more privileges'`);
        await queryRunner.query(`CREATE TABLE "user_profiles" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "firstName" character varying(100) NOT NULL, "lastName" character varying(100) NOT NULL, "phone" character varying(20) NOT NULL, "isPhoneVerified" boolean NOT NULL DEFAULT false, "profilePicture" text, "language" character varying(10) NOT NULL DEFAULT 'en', "timezone" character varying(50) NOT NULL DEFAULT 'Africa/Lagos', "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8481388d6325e752cd4d7e26c6d" UNIQUE ("userId"), CONSTRAINT "UQ_dceea64a755bbbc3b64f0ec018d" UNIQUE ("phone"), CONSTRAINT "REL_8481388d6325e752cd4d7e26c6" UNIQUE ("userId"), CONSTRAINT "PK_1ec6662219f4605723f1e41b6cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_dceea64a755bbbc3b64f0ec018" ON "user_profiles" ("phone") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8481388d6325e752cd4d7e26c6" ON "user_profiles" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."user_kyc_status_enum" AS ENUM('pending', 'in_progress', 'verified', 'failed', 'rejected')`);
        await queryRunner.query(`CREATE TYPE "public"."user_kyc_verificationprovider_enum" AS ENUM('dojah', 'manual')`);
        await queryRunner.query(`CREATE TABLE "user_kyc" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "bvn" character varying(255), "status" "public"."user_kyc_status_enum" NOT NULL DEFAULT 'pending', "verificationProvider" "public"."user_kyc_verificationprovider_enum", "verificationReference" character varying(255), "verificationResponse" jsonb, "verifiedAt" TIMESTAMP, "failureReason" text, "adminNotes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_4e246b1a648a4bf051e4d082eb5" UNIQUE ("userId"), CONSTRAINT "REL_4e246b1a648a4bf051e4d082eb" UNIQUE ("userId"), CONSTRAINT "PK_96852e5a0116c49c1507faae57a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_eaeb0d7330ff6e5c87d4f9d628" ON "user_kyc" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_4e246b1a648a4bf051e4d082eb" ON "user_kyc" ("userId") `);
        await queryRunner.query(`CREATE TABLE "user_security" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "pin" character varying(255), "pinFailedAttempts" integer NOT NULL DEFAULT '0', "pinLockedUntil" TIMESTAMP, "deviceId" character varying(255), "latitude" numeric(10,8), "longitude" numeric(11,8), "twoFactorEnabled" boolean NOT NULL DEFAULT false, "twoFactorSecret" character varying(255), "trustedDevices" jsonb, "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_2c6ad367fcb763798ea480097b1" UNIQUE ("userId"), CONSTRAINT "REL_2c6ad367fcb763798ea480097b" UNIQUE ("userId"), CONSTRAINT "PK_93872b376b45c4ef21b6ace7314" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2c6ad367fcb763798ea480097b" ON "user_security" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."user_onboarding_currentstep_enum" AS ENUM('personal_information', 'phone_verification', 'kyc_verification', 'business_information', 'authentication_pin')`);
        await queryRunner.query(`CREATE TABLE "user_onboarding" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "currentStep" "public"."user_onboarding_currentstep_enum" NOT NULL DEFAULT 'personal_information', "isCompleted" boolean NOT NULL DEFAULT false, "completedAt" TIMESTAMP, "progressPercentage" smallint NOT NULL DEFAULT '0', "skippedSteps" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_f3e7bb4005372c40076e8af93ca" UNIQUE ("userId"), CONSTRAINT "REL_f3e7bb4005372c40076e8af93c" UNIQUE ("userId"), CONSTRAINT "PK_257c3b267f3b16db9ec6122d10d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f3e7bb4005372c40076e8af93c" ON "user_onboarding" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."wallets_provider_enum" AS ENUM('paystack')`);
        await queryRunner.query(`CREATE TYPE "public"."wallets_status_enum" AS ENUM('pending', 'active', 'inactive', 'suspended', 'closed')`);
        await queryRunner.query(`CREATE TABLE "wallets" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "provider" "public"."wallets_provider_enum" NOT NULL DEFAULT 'paystack', "providerCustomerId" character varying(255), "providerAccountId" character varying(255), "accountNumber" character varying(20) NOT NULL, "accountName" character varying(255) NOT NULL, "bankName" character varying(100) NOT NULL, "bankCode" character varying(10) NOT NULL, "status" "public"."wallets_status_enum" NOT NULL DEFAULT 'pending', "availableBalance" numeric(15,2) NOT NULL DEFAULT '0', "pendingBalance" numeric(15,2) NOT NULL DEFAULT '0', "ledgerBalance" numeric(15,2) NOT NULL DEFAULT '0', "currency" character varying(3) NOT NULL DEFAULT 'NGN', "providerMetadata" jsonb, "activatedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_2ecdb33f23e9a6fc392025c0b97" UNIQUE ("userId"), CONSTRAINT "UQ_444a7f9feac3d2154c45875d0a1" UNIQUE ("accountNumber"), CONSTRAINT "REL_2ecdb33f23e9a6fc392025c0b9" UNIQUE ("userId"), CONSTRAINT "PK_8402e5df5a30a229380e83e4f7e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e83ee448888683883666ce553e" ON "wallets" ("providerCustomerId") `);
        await queryRunner.query(`CREATE INDEX "IDX_79e9c3c76ea89e2334986f1e32" ON "wallets" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_444a7f9feac3d2154c45875d0a" ON "wallets" ("accountNumber") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2ecdb33f23e9a6fc392025c0b9" ON "wallets" ("userId") `);
        await queryRunner.query(`CREATE TYPE "public"."bank_accounts_status_enum" AS ENUM('pending', 'verified', 'failed', 'inactive')`);
        await queryRunner.query(`CREATE TABLE "bank_accounts" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "accountNumber" character varying(20) NOT NULL, "accountName" character varying(255) NOT NULL, "bankName" character varying(100) NOT NULL, "bankCode" character varying(10) NOT NULL, "status" "public"."bank_accounts_status_enum" NOT NULL DEFAULT 'pending', "isPrimary" boolean NOT NULL DEFAULT false, "providerRecipientCode" character varying(255), "verificationProvider" character varying(50), "verificationResponse" jsonb, "verifiedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c872de764f2038224a013ff25ed" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_9dcc47dcf41085bb47109de56e" ON "bank_accounts" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f048bcb5cb3c77a3d765ebc3c1" ON "bank_accounts" ("accountNumber", "bankCode") `);
        await queryRunner.query(`CREATE INDEX "IDX_40666d1bcf2deba09f1f415293" ON "bank_accounts" ("userId", "isPrimary") `);
        await queryRunner.query(`CREATE TYPE "public"."users_usertype_enum" AS ENUM('user', 'admin', 'super_admin')`);
        await queryRunner.query(`CREATE TYPE "public"."users_status_enum" AS ENUM('active', 'inactive', 'suspended', 'banned')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" SERIAL NOT NULL, "email" character varying NOT NULL, "password" character varying NOT NULL, "userType" "public"."users_usertype_enum" NOT NULL DEFAULT 'user', "roleId" integer, "status" "public"."users_status_enum" NOT NULL DEFAULT 'active', "statusReason" character varying, "suspendedUntil" TIMESTAMP WITH TIME ZONE, "businessId" integer, "isEmailVerified" boolean NOT NULL DEFAULT false, "isPhoneVerified" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "createdBy" integer, "suspendedBy" integer, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_78725ac7117e7526e028014606b" UNIQUE ("businessId"), CONSTRAINT "REL_78725ac7117e7526e028014606" UNIQUE ("businessId"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id")); COMMENT ON COLUMN "users"."userType" IS 'User type: user or admin'; COMMENT ON COLUMN "users"."statusReason" IS 'Reason for suspension/ban'`);
        await queryRunner.query(`CREATE TABLE "leads" ("id" SERIAL NOT NULL, "name" character varying, "email" character varying NOT NULL, "phone" character varying, "formId" integer NOT NULL, "businessId" integer NOT NULL, "formResponses" jsonb, "ipAddress" character varying, "userAgent" text, "referrer" character varying, "utmParameters" jsonb, "country" character varying, "city" character varying, "latitude" double precision, "longitude" double precision, "deviceType" character varying, "browser" character varying, "operatingSystem" character varying, "isContacted" boolean NOT NULL DEFAULT false, "status" character varying, "notes" text, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_cd102ed7a9a4ca7d4d8bfeba406" PRIMARY KEY ("id")); COMMENT ON COLUMN "leads"."ipAddress" IS 'IP address of the submitter'; COMMENT ON COLUMN "leads"."userAgent" IS 'User agent string (browser/device info)'; COMMENT ON COLUMN "leads"."referrer" IS 'Referrer URL - where the user came from'; COMMENT ON COLUMN "leads"."utmParameters" IS 'UTM parameters for marketing attribution'; COMMENT ON COLUMN "leads"."country" IS 'Country derived from IP'; COMMENT ON COLUMN "leads"."city" IS 'City derived from IP'; COMMENT ON COLUMN "leads"."latitude" IS 'Latitude from geolocation'; COMMENT ON COLUMN "leads"."longitude" IS 'Longitude from geolocation'; COMMENT ON COLUMN "leads"."deviceType" IS 'Device type: mobile, tablet, desktop'; COMMENT ON COLUMN "leads"."browser" IS 'Browser name'; COMMENT ON COLUMN "leads"."operatingSystem" IS 'Operating system'; COMMENT ON COLUMN "leads"."isContacted" IS 'Whether the lead has been contacted'; COMMENT ON COLUMN "leads"."status" IS 'Status: new, contacted, qualified, converted, lost'; COMMENT ON COLUMN "leads"."notes" IS 'Notes added by business owner'; COMMENT ON COLUMN "leads"."metadata" IS 'Custom metadata'`);
        await queryRunner.query(`CREATE TABLE "lead-forms" ("id" SERIAL NOT NULL, "title" character varying NOT NULL, "description" text, "button_text" character varying NOT NULL, "inputs" jsonb, "logoUrl" character varying, "isActive" boolean NOT NULL DEFAULT true, "slug" character varying NOT NULL, "publicId" character varying NOT NULL, "requireEmailVerification" boolean NOT NULL DEFAULT false, "enableCaptcha" boolean NOT NULL DEFAULT false, "sendEmailNotification" boolean NOT NULL DEFAULT true, "successMessage" character varying, "redirectUrl" character varying, "submissionCount" integer NOT NULL DEFAULT '0', "maxSubmissions" integer NOT NULL DEFAULT '0', "allowedDomains" jsonb, "customStyling" jsonb, "businessId" integer NOT NULL, "createdBy" integer NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_5185f5a19d5159aca97cb080915" UNIQUE ("slug"), CONSTRAINT "UQ_08be2ee9a486a9b9e0e5667844b" UNIQUE ("publicId"), CONSTRAINT "PK_51517a1dca31b9466b4be664034" PRIMARY KEY ("id")); COMMENT ON COLUMN "lead-forms"."slug" IS 'Unique slug for public URL access'; COMMENT ON COLUMN "lead-forms"."publicId" IS 'Random public ID for sharing'; COMMENT ON COLUMN "lead-forms"."requireEmailVerification" IS 'Require email verification before accepting lead'; COMMENT ON COLUMN "lead-forms"."enableCaptcha" IS 'Enable CAPTCHA verification'; COMMENT ON COLUMN "lead-forms"."sendEmailNotification" IS 'Send email notification on new lead'; COMMENT ON COLUMN "lead-forms"."successMessage" IS 'Custom success message after submission'; COMMENT ON COLUMN "lead-forms"."redirectUrl" IS 'Redirect URL after successful submission'; COMMENT ON COLUMN "lead-forms"."submissionCount" IS 'Total number of submissions received'; COMMENT ON COLUMN "lead-forms"."maxSubmissions" IS 'Maximum submissions allowed (0 = unlimited)'; COMMENT ON COLUMN "lead-forms"."allowedDomains" IS 'Allowed domains for CORS (for embedded forms)'; COMMENT ON COLUMN "lead-forms"."customStyling" IS 'Custom styling for embedded form'`);
        await queryRunner.query(`CREATE TYPE "public"."business_payment_accounts_provider_enum" AS ENUM('paystack')`);
        await queryRunner.query(`CREATE TYPE "public"."business_payment_accounts_status_enum" AS ENUM('pending', 'active', 'inactive', 'suspended')`);
        await queryRunner.query(`CREATE TABLE "business_payment_accounts" ("id" SERIAL NOT NULL, "businessId" integer NOT NULL, "provider" "public"."business_payment_accounts_provider_enum" NOT NULL DEFAULT 'paystack', "providerSubaccountCode" character varying(255) NOT NULL, "status" "public"."business_payment_accounts_status_enum" NOT NULL DEFAULT 'pending', "settlementBankAccountId" integer, "providerMetadata" jsonb, "activatedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_2bccc958611f57d6dcd621a733c" UNIQUE ("businessId"), CONSTRAINT "UQ_fc1905d33f79be3fd5c30499856" UNIQUE ("providerSubaccountCode"), CONSTRAINT "REL_2bccc958611f57d6dcd621a733" UNIQUE ("businessId"), CONSTRAINT "PK_107a4f2dbcf9fb3d62f12f6a29b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_85d276b69bd948f6722e85e5b6" ON "business_payment_accounts" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fc1905d33f79be3fd5c3049985" ON "business_payment_accounts" ("providerSubaccountCode") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2bccc958611f57d6dcd621a733" ON "business_payment_accounts" ("businessId") `);
        await queryRunner.query(`CREATE TYPE "public"."business_settlement_configs_schedule_enum" AS ENUM('instant', 'daily', 'weekly', 'monthly', 'manual')`);
        await queryRunner.query(`CREATE TABLE "business_settlement_configs" ("id" SERIAL NOT NULL, "businessId" integer NOT NULL, "schedule" "public"."business_settlement_configs_schedule_enum" NOT NULL DEFAULT 'manual', "minimumSettlementAmount" numeric(15,2) NOT NULL DEFAULT '1000', "defaultBankAccountId" integer, "autoSettlementEnabled" boolean NOT NULL DEFAULT true, "holdPeriodDays" smallint NOT NULL DEFAULT '0', "lastSettlementDate" TIMESTAMP, "nextSettlementDate" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_99beea24e18ed0b25f0203db191" UNIQUE ("businessId"), CONSTRAINT "REL_99beea24e18ed0b25f0203db19" UNIQUE ("businessId"), CONSTRAINT "PK_01a44f7672a189cac5edda8c180" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3315c15893281839b388c327b5" ON "business_settlement_configs" ("nextSettlementDate") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_99beea24e18ed0b25f0203db19" ON "business_settlement_configs" ("businessId") `);
        await queryRunner.query(`CREATE TYPE "public"."product_sizes_measurement_enum" AS ENUM('SIZE', 'LABEL')`);
        await queryRunner.query(`CREATE TABLE "product_sizes" ("id" SERIAL NOT NULL, "measurement" "public"."product_sizes_measurement_enum" NOT NULL, "value" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "productId" integer, CONSTRAINT "PK_19c3d021f81c5b1ff367bad6164" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" SERIAL NOT NULL, "name" character varying NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8b0be371d28245da6e4f4b61878" UNIQUE ("name"), CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8b0be371d28245da6e4f4b6187" ON "categories" ("name") `);
        await queryRunner.query(`CREATE TABLE "product_variants" ("id" SERIAL NOT NULL, "productId" integer NOT NULL, "sku" character varying(100) NOT NULL, "variantName" character varying(255) NOT NULL, "options" jsonb, "price" numeric(10,2), "compareAtPrice" numeric(10,2), "costPrice" numeric(10,2), "quantityInStock" integer NOT NULL DEFAULT '0', "reservedQuantity" integer NOT NULL DEFAULT '0', "lowStockThreshold" integer NOT NULL DEFAULT '5', "allowBackorder" boolean NOT NULL DEFAULT false, "weightGrams" numeric(8,2), "barcode" character varying(100), "isActive" boolean NOT NULL DEFAULT true, "isDefault" boolean NOT NULL DEFAULT false, "imageIds" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_281e3f2c55652d6a22c0aa59fd7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_74f84d49e67995a1e46c402eab" ON "product_variants" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_cb151f7020703dd7b20656b7bb" ON "product_variants" ("quantityInStock") `);
        await queryRunner.query(`CREATE INDEX "IDX_46f236f21640f9da218a063a86" ON "product_variants" ("sku") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_96473e185ba3f4f12dd0b2734d" ON "product_variants" ("productId", "sku") `);
        await queryRunner.query(`CREATE TABLE "product_images" ("id" SERIAL NOT NULL, "productId" integer NOT NULL, "imageUrl" text NOT NULL, "thumbnailUrl" text, "altText" character varying(255), "sortOrder" smallint NOT NULL DEFAULT '0', "isPrimary" boolean NOT NULL DEFAULT false, "cloudinaryPublicId" character varying(255), "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1974264ea7265989af8392f63a1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_0e608cfeddd2708513ff81b73d" ON "product_images" ("isPrimary") `);
        await queryRunner.query(`CREATE INDEX "IDX_a47d8b28fa544e88fb805b3b33" ON "product_images" ("productId", "sortOrder") `);
        await queryRunner.query(`CREATE TABLE "products" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "businessId" integer NOT NULL, "imageUrls" text, "name" character varying NOT NULL, "categoryId" integer NOT NULL, "description" text, "price" numeric(10,2) NOT NULL, "quantityInStock" integer NOT NULL DEFAULT '0', "hasVariation" boolean NOT NULL DEFAULT false, "colors" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id")); COMMENT ON COLUMN "products"."imageUrls" IS 'Array of image URLs (deprecated - use images relation)'; COMMENT ON COLUMN "products"."hasVariation" IS 'Does this product include size or color variations?'`);
        await queryRunner.query(`CREATE INDEX "IDX_99d90c2a483d79f3b627fb1d5e" ON "products" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_359bd8406fbfb50e3ea42b5631" ON "products" ("businessId") `);
        await queryRunner.query(`CREATE INDEX "IDX_4c9fb58de893725258746385e1" ON "products" ("name") `);
        await queryRunner.query(`CREATE INDEX "IDX_ff56834e735fa78a15d0cf2192" ON "products" ("categoryId") `);
        await queryRunner.query(`CREATE INDEX "IDX_75895eeb1903f8a17816dafe0a" ON "products" ("price") `);
        await queryRunner.query(`CREATE INDEX "IDX_0591b4a1abb428c6d86744cc0a" ON "products" ("quantityInStock") `);
        await queryRunner.query(`CREATE INDEX "IDX_63fcb3d8806a6efd53dbc67430" ON "products" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_69e49df9a08f8ded911758822f" ON "products" ("userId", "businessId") `);
        await queryRunner.query(`CREATE TYPE "public"."order_items_status_enum" AS ENUM('pending', 'processing', 'shipped', 'delivered', 'cancelled', 'returned', 'refunded')`);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" SERIAL NOT NULL, "orderId" integer NOT NULL, "productId" integer NOT NULL, "variantId" integer, "productName" character varying NOT NULL, "productDescription" text, "price" numeric(10,2) NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "subtotal" numeric(10,2) NOT NULL, "color" character varying, "size" character varying, "imageUrls" text, "status" "public"."order_items_status_enum" NOT NULL DEFAULT 'pending', "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f1d359a55923bb45b057fbdab0" ON "order_items" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cdb99c05982d5191ac8465ac01" ON "order_items" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_516736b9807228bb17b2d0a3e2" ON "order_items" ("variantId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f421c8981cca05954f98667134" ON "order_items" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."order_status_history_status_enum" AS ENUM('pending', 'payment_initiated', 'paid', 'confirmed', 'processing', 'shipped', 'delivered', 'completed', 'cancelled', 'returned', 'refunded')`);
        await queryRunner.query(`CREATE TYPE "public"."order_status_history_previousstatus_enum" AS ENUM('pending', 'payment_initiated', 'paid', 'confirmed', 'processing', 'shipped', 'delivered', 'completed', 'cancelled', 'returned', 'refunded')`);
        await queryRunner.query(`CREATE TABLE "order_status_history" ("id" SERIAL NOT NULL, "orderId" integer NOT NULL, "status" "public"."order_status_history_status_enum" NOT NULL, "previousStatus" "public"."order_status_history_previousstatus_enum", "triggeredBy" character varying(50) NOT NULL, "triggeredByUserId" integer, "notes" text, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e6c66d853f155531985fc4f6ec8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a025fc2421d2553fb5aaaa77dc" ON "order_status_history" ("triggeredByUserId") `);
        await queryRunner.query(`CREATE INDEX "IDX_41a834150f6ba631f6e9e6f13c" ON "order_status_history" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_be366be57f21391e49f42e0b18" ON "order_status_history" ("orderId", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."order_payments_provider_enum" AS ENUM('paystack')`);
        await queryRunner.query(`CREATE TYPE "public"."order_payments_paymentmethod_enum" AS ENUM('bank_transfer', 'card', 'wallet', 'ussd', 'cash_on_delivery')`);
        await queryRunner.query(`CREATE TYPE "public"."order_payments_status_enum" AS ENUM('pending', 'initiated', 'processing', 'paid', 'failed', 'expired', 'refunded', 'partially_refunded')`);
        await queryRunner.query(`CREATE TABLE "order_payments" ("id" SERIAL NOT NULL, "orderId" integer NOT NULL, "paymentReference" character varying(50) NOT NULL, "provider" "public"."order_payments_provider_enum" NOT NULL DEFAULT 'paystack', "providerReference" character varying(255), "paymentMethod" "public"."order_payments_paymentmethod_enum" NOT NULL, "status" "public"."order_payments_status_enum" NOT NULL DEFAULT 'pending', "amount" numeric(15,2) NOT NULL, "fee" numeric(15,2) NOT NULL DEFAULT '0', "netAmount" numeric(15,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'NGN', "authorizationUrl" text, "accessCode" character varying(255), "cardDetails" jsonb, "bankDetails" jsonb, "customerIp" character varying(45), "providerResponse" jsonb, "initiatedAt" TIMESTAMP, "paidAt" TIMESTAMP, "failureReason" text, "expiresAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_abca480893311e20150f01b2f15" UNIQUE ("orderId"), CONSTRAINT "UQ_11dec6a1b92ef13a86992f05220" UNIQUE ("paymentReference"), CONSTRAINT "REL_abca480893311e20150f01b2f1" UNIQUE ("orderId"), CONSTRAINT "PK_bc14b014a69d39c7bbc4a154b69" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_fbc1adaaa870de1aae3da1903c" ON "order_payments" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_b0a057dbf38cec095c3113622a" ON "order_payments" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_11dec6a1b92ef13a86992f0522" ON "order_payments" ("paymentReference") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_abca480893311e20150f01b2f1" ON "order_payments" ("orderId") `);
        await queryRunner.query(`CREATE TABLE "order_shipments" ("id" SERIAL NOT NULL, "orderId" integer NOT NULL, "carrier" character varying(100), "trackingNumber" character varying(255), "trackingUrl" text, "status" character varying(50) NOT NULL DEFAULT 'PENDING', "estimatedDeliveryDate" TIMESTAMP, "deliveredAt" TIMESTAMP, "recipientName" character varying(255), "recipientPhone" character varying(20), "shippingAddress" text, "proofOfDelivery" text, "deliveryNotes" text, "carrierMetadata" jsonb, "shippedAt" TIMESTAMP, "createdBy" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5ad728999743f02e46c31e8189c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_cead94ae651bf71a9ac18199d1" ON "order_shipments" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_fb7744b02af865e1cf3d329482" ON "order_shipments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_19d9c6672e6f155f97257c34a8" ON "order_shipments" ("trackingNumber") `);
        await queryRunner.query(`CREATE INDEX "IDX_fde014e470812e051024062395" ON "order_shipments" ("orderId") `);
        await queryRunner.query(`CREATE TYPE "public"."order_refunds_refundtype_enum" AS ENUM('full', 'partial')`);
        await queryRunner.query(`CREATE TYPE "public"."order_refunds_refundmethod_enum" AS ENUM('original_payment', 'wallet', 'bank_account')`);
        await queryRunner.query(`CREATE TYPE "public"."order_refunds_status_enum" AS ENUM('requested', 'pending_approval', 'approved', 'processing', 'completed', 'partially_completed', 'failed', 'rejected')`);
        await queryRunner.query(`CREATE TYPE "public"."order_refunds_reason_enum" AS ENUM('customer_request', 'out_of_stock', 'damaged_product', 'wrong_item', 'merchant_cancelled', 'payment_issue', 'fraud', 'other')`);
        await queryRunner.query(`CREATE TABLE "order_refunds" ("id" SERIAL NOT NULL, "orderId" integer NOT NULL, "refundReference" character varying(50) NOT NULL, "refundType" "public"."order_refunds_refundtype_enum" NOT NULL, "refundMethod" "public"."order_refunds_refundmethod_enum" NOT NULL DEFAULT 'original_payment', "status" "public"."order_refunds_status_enum" NOT NULL DEFAULT 'requested', "amountRequested" numeric(15,2) NOT NULL, "amountApproved" numeric(15,2), "amountRefunded" numeric(15,2), "currency" character varying(3) NOT NULL DEFAULT 'NGN', "reason" "public"."order_refunds_reason_enum" NOT NULL, "reasonNotes" text, "requestedBy" integer, "approvedBy" integer, "processedBy" integer, "platformRefundReference" character varying(255), "businessRefundReference" character varying(255), "providerMetadata" jsonb, "requestedAt" TIMESTAMP, "approvedAt" TIMESTAMP, "processedAt" TIMESTAMP, "completedAt" TIMESTAMP, "failureReason" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_fc74256b145a0f94ef592d37762" UNIQUE ("refundReference"), CONSTRAINT "PK_f8c501d1232e93e00aac466a279" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_abde04a1ead8cce748c0c9c6e0" ON "order_refunds" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_26ba92d70706a998979a107c46" ON "order_refunds" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fc74256b145a0f94ef592d3776" ON "order_refunds" ("refundReference") `);
        await queryRunner.query(`CREATE INDEX "IDX_1d266acc6f94a5d28bf7bfa169" ON "order_refunds" ("orderId") `);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('pending', 'payment_initiated', 'paid', 'confirmed', 'processing', 'shipped', 'delivered', 'completed', 'cancelled', 'returned', 'refunded')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_paymentstatus_enum" AS ENUM('pending', 'initiated', 'processing', 'paid', 'failed', 'expired', 'refunded', 'partially_refunded')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_paymentmethod_enum" AS ENUM('bank_transfer', 'card', 'wallet', 'ussd', 'cash_on_delivery')`);
        await queryRunner.query(`CREATE TYPE "public"."orders_deliverymethod_enum" AS ENUM('standard', 'express', 'pickup')`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" SERIAL NOT NULL, "orderReference" character varying NOT NULL, "userId" integer, "businessId" integer NOT NULL, "transactionReference" character varying, "customerName" character varying NOT NULL, "deliveryAddress" text NOT NULL, "state" character varying NOT NULL, "city" character varying, "customerEmail" character varying NOT NULL, "customerPhoneNumber" character varying NOT NULL, "status" "public"."orders_status_enum" NOT NULL DEFAULT 'pending', "paymentStatus" "public"."orders_paymentstatus_enum" NOT NULL DEFAULT 'pending', "paymentMethod" "public"."orders_paymentmethod_enum" NOT NULL, "deliveryMethod" "public"."orders_deliverymethod_enum" NOT NULL, "subtotal" numeric(10,2) NOT NULL, "shippingFee" numeric(10,2) NOT NULL, "tax" numeric(10,2) NOT NULL, "discount" numeric(10,2) NOT NULL DEFAULT '0', "total" numeric(10,2) NOT NULL, "notes" text, "isGuestOrder" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "UQ_a8bdfcfdf8520db858774ab453c" UNIQUE ("orderReference"), CONSTRAINT "UQ_3b5b32cf9f908e4cf776a94d2a9" UNIQUE ("transactionReference"), CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_151b79a83ba240b0cb31b2302d" ON "orders" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_778777c5d7d56ed1bbaa907b8e" ON "orders" ("businessId") `);
        await queryRunner.query(`CREATE INDEX "IDX_19a7638af058ba9a727b100869" ON "orders" ("customerEmail") `);
        await queryRunner.query(`CREATE INDEX "IDX_01b20118a3f640214e7a8a6b29" ON "orders" ("paymentStatus") `);
        await queryRunner.query(`CREATE INDEX "IDX_775c9f06fc27ae3ff8fb26f2c4" ON "orders" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_1f4b9818a08b822a31493fdee9" ON "orders" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_5025e0259ec0b1ffb5f0ea6685" ON "orders" ("userId", "businessId") `);
        await queryRunner.query(`CREATE TYPE "public"."settlements_status_enum" AS ENUM('pending', 'processing', 'completed', 'failed', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "settlements" ("id" SERIAL NOT NULL, "settlementReference" character varying(50) NOT NULL, "businessId" integer NOT NULL, "orderId" integer NOT NULL, "status" "public"."settlements_status_enum" NOT NULL DEFAULT 'pending', "orderAmount" numeric(15,2) NOT NULL, "platformFee" numeric(15,2) NOT NULL, "gatewayFee" numeric(15,2) NOT NULL DEFAULT '0', "settlementAmount" numeric(15,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'NGN', "bankAccountId" integer, "transferProvider" character varying(50), "transferReference" character varying(255), "providerMetadata" jsonb, "settledAt" TIMESTAMP, "failureReason" text, "retryCount" smallint NOT NULL DEFAULT '0', "nextRetryAt" TIMESTAMP, "initiatedBy" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_483cc42916e1d0847b3fb08092d" UNIQUE ("settlementReference"), CONSTRAINT "UQ_688cf34e61f3b2dc58a1fa91f2b" UNIQUE ("orderId"), CONSTRAINT "REL_688cf34e61f3b2dc58a1fa91f2" UNIQUE ("orderId"), CONSTRAINT "PK_5f523ce152b84e818bff9467aab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_86077b8251cb7c44bb836a314e" ON "settlements" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_483cc42916e1d0847b3fb08092" ON "settlements" ("settlementReference") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_688cf34e61f3b2dc58a1fa91f2" ON "settlements" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7e1995ebbedd550e18c457548b" ON "settlements" ("businessId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "businesses" ("id" SERIAL NOT NULL, "businessName" character varying NOT NULL, "businessTypeId" integer NOT NULL, "businessDescription" character varying, "location" character varying NOT NULL, "logo" character varying, "userId" integer NOT NULL, "coverImage" character varying, "storeName" character varying, "slug" character varying, "heroText" character varying, "storeColor" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_5ba6375fdc72387a2d2d0bb7720" UNIQUE ("userId"), CONSTRAINT "UQ_6972aa4a4d17d2d31f79c0b8967" UNIQUE ("storeName"), CONSTRAINT "UQ_82ca19bc20713fdfa72626a5da0" UNIQUE ("slug"), CONSTRAINT "REL_5ba6375fdc72387a2d2d0bb772" UNIQUE ("userId"), CONSTRAINT "PK_bc1bf63498dd2368ce3dc8686e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_business_slug" ON "businesses" ("slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_business_storeName" ON "businesses" ("storeName") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" SERIAL NOT NULL, "entityType" character varying(50) NOT NULL, "entityId" integer NOT NULL, "action" character varying(50) NOT NULL, "performedBy" integer, "actorType" character varying(20) NOT NULL DEFAULT 'USER', "ipAddress" character varying(45), "userAgent" text, "beforeState" jsonb, "afterState" jsonb, "changedFields" jsonb, "reason" text, "metadata" jsonb, "requestId" character varying(255), "severity" character varying(20) NOT NULL DEFAULT 'INFO', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8ddc86298ac7fadad468b28d83" ON "audit_logs" ("ipAddress") `);
        await queryRunner.query(`CREATE INDEX "IDX_c69efb19bf127c97e6740ad530" ON "audit_logs" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_a8bd8d95914d6228770fe87b8a" ON "audit_logs" ("performedBy") `);
        await queryRunner.query(`CREATE INDEX "IDX_13c69424c440a0e765053feb4b" ON "audit_logs" ("entityType", "entityId") `);
        await queryRunner.query(`CREATE TABLE "system_events" ("id" SERIAL NOT NULL, "eventType" character varying(50) NOT NULL, "source" character varying(50) NOT NULL, "status" character varying(20) NOT NULL, "severity" character varying(20) NOT NULL DEFAULT 'INFO', "message" text NOT NULL, "relatedEntityType" character varying(50), "relatedEntityId" integer, "requestPayload" jsonb, "responsePayload" jsonb, "errorDetails" jsonb, "httpStatusCode" smallint, "durationMs" integer, "ipAddress" character varying(45), "signatureValid" boolean, "retryCount" smallint NOT NULL DEFAULT '0', "nextRetryAt" TIMESTAMP, "requestId" character varying(255), "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_f28cae54c57b2887d94a4aa745e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c4c8f6c19ceb46ad1279b75fcc" ON "system_events" ("source") `);
        await queryRunner.query(`CREATE INDEX "IDX_05e9f830e250583c68cfe3a5aa" ON "system_events" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_06a528c9ad99e80e86baf8fa44" ON "system_events" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_2ea511240853f023d2219bc661" ON "system_events" ("eventType") `);
        await queryRunner.query(`CREATE TYPE "public"."otps_otptype_enum" AS ENUM('email', 'phone')`);
        await queryRunner.query(`CREATE TYPE "public"."otps_purpose_enum" AS ENUM('phone_verification', 'password_reset', 'email_verification', 'pin_creation')`);
        await queryRunner.query(`CREATE TABLE "otps" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "otp" character varying(50) NOT NULL, "otpType" "public"."otps_otptype_enum" NOT NULL, "purpose" "public"."otps_purpose_enum" NOT NULL DEFAULT 'phone_verification', "expiresAt" TIMESTAMP NOT NULL, "isUsed" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_91fef5ed60605b854a2115d2410" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."user_progress_event_enum" AS ENUM('TRANSACTION_PIN_CREATED', 'FIRST_PRODUCT_CREATED', 'BUSINESS_INFO_UPDATED', 'BUSINESS_LINK_SHARED')`);
        await queryRunner.query(`CREATE TABLE "user_progress" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "event" "public"."user_progress_event_enum" NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7b5eb2436efb0051fdf05cbe839" PRIMARY KEY ("id")); COMMENT ON COLUMN "user_progress"."event" IS 'Type of progress milestone'`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_type_enum" AS ENUM('ORDER_PAYMENT', 'SETTLEMENT', 'WITHDRAWAL', 'REFUND', 'WALLET_FUNDING', 'FEE')`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_flow_enum" AS ENUM('CREDIT', 'DEBIT')`);
        await queryRunner.query(`CREATE TYPE "public"."transactions_status_enum" AS ENUM('PENDING', 'SUCCESS', 'FAILED', 'REVERSED')`);
        await queryRunner.query(`CREATE TABLE "transactions" ("id" SERIAL NOT NULL, "reference" character varying NOT NULL, "userId" integer, "businessId" integer, "orderId" integer, "type" "public"."transactions_type_enum" NOT NULL, "flow" "public"."transactions_flow_enum" NOT NULL, "status" "public"."transactions_status_enum" NOT NULL DEFAULT 'PENDING', "amount" numeric(15,2) NOT NULL, "fee" numeric(15,2) NOT NULL DEFAULT '0', "netAmount" numeric(15,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'NGN', "paymentMethod" character varying, "paymentProvider" character varying, "providerReference" character varying, "description" text, "senderAccountNumber" character varying, "senderAccountName" character varying, "senderBankName" character varying, "recipientAccountNumber" character varying, "recipientAccountName" character varying, "recipientBankName" character varying, "balanceBefore" numeric(15,2) NOT NULL DEFAULT '0', "balanceAfter" numeric(15,2) NOT NULL DEFAULT '0', "metadata" json, "providerResponse" json, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "settledAt" TIMESTAMP, CONSTRAINT "UQ_dd85cc865e0c3d5d4be095d3f3f" UNIQUE ("reference"), CONSTRAINT "PK_a219afd8dd77ed80f5a862f1db9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6bb58f2b6e30cb51a6504599f4" ON "transactions" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_9f24c9c8611e077a48a0645e3d" ON "transactions" ("businessId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2fdbbae70ff802bc8b703ee7c5" ON "transactions" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_2d5fa024a84dceb158b2b95f34" ON "transactions" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_da87c55b3bbbe96c6ed88ea7ee" ON "transactions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_e744417ceb0b530285c08f3865" ON "transactions" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_85d65d236f62b4496cd115f097" ON "transactions" ("userId", "businessId") `);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" SERIAL NOT NULL, "userId" integer NOT NULL, "guestName" character varying, "guestEmail" character varying, "guestPhone" character varying, "businessId" integer NOT NULL, "productId" integer NOT NULL, "orderId" integer NOT NULL, "orderItemId" integer NOT NULL, "review" text NOT NULL, "ratings" integer NOT NULL, "imageUrls" text, "isVisible" boolean NOT NULL DEFAULT true, "isVerifiedPurchase" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id")); COMMENT ON COLUMN "reviews"."guestName" IS 'Guest reviewer name (when userId is null)'; COMMENT ON COLUMN "reviews"."guestEmail" IS 'Guest reviewer email (when userId is null)'; COMMENT ON COLUMN "reviews"."guestPhone" IS 'Guest reviewer phone (when userId is null)'; COMMENT ON COLUMN "reviews"."ratings" IS 'Rating between 1-5'; COMMENT ON COLUMN "reviews"."imageUrls" IS 'Array of image URLs'`);
        await queryRunner.query(`CREATE INDEX "IDX_7ed5659e7139fc8bc039198cc1" ON "reviews" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_058c6448644b27a8e63fd03106" ON "reviews" ("guestEmail") `);
        await queryRunner.query(`CREATE INDEX "IDX_d17ce9c119d29c7ec8c884044c" ON "reviews" ("businessId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a6b3c434392f5d10ec17104366" ON "reviews" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_53a68dc905777554b7f702791f" ON "reviews" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1e6c554d615dd5a5bf0e11ee0e" ON "reviews" ("orderItemId") `);
        await queryRunner.query(`CREATE TYPE "public"."email_queue_emailtype_enum" AS ENUM('order_created', 'order_confirmed', 'order_shipped', 'order_delivered', 'order_cancelled', 'payment_success', 'payment_failed', 'refund_processed', 'settlement_processed', 'low_stock', 'new_review', 'cart_abandonment', 'custom')`);
        await queryRunner.query(`CREATE TYPE "public"."email_queue_status_enum" AS ENUM('queued', 'sending', 'sent', 'failed', 'bounced')`);
        await queryRunner.query(`CREATE TYPE "public"."email_queue_provider_enum" AS ENUM('mailgun', 'resend', 'sendgrid')`);
        await queryRunner.query(`CREATE TABLE "email_queue" ("id" SERIAL NOT NULL, "emailType" "public"."email_queue_emailtype_enum" NOT NULL, "status" "public"."email_queue_status_enum" NOT NULL DEFAULT 'queued', "provider" "public"."email_queue_provider_enum" NOT NULL DEFAULT 'resend', "recipientEmail" character varying(255) NOT NULL, "recipientName" character varying(255), "senderEmail" character varying(255) NOT NULL DEFAULT 'noreply@qkly.com', "senderName" character varying(255) NOT NULL DEFAULT 'Qkly', "subject" character varying(500) NOT NULL, "htmlBody" text NOT NULL, "textBody" text, "templateId" character varying(100), "templateVariables" jsonb, "attachments" jsonb, "relatedEntityType" character varying(50), "relatedEntityId" integer, "scheduledFor" TIMESTAMP, "sentAt" TIMESTAMP, "providerMessageId" character varying(255), "providerResponse" jsonb, "retryCount" smallint NOT NULL DEFAULT '0', "maxRetries" smallint NOT NULL DEFAULT '3', "nextRetryAt" TIMESTAMP, "failureReason" text, "priority" smallint NOT NULL DEFAULT '5', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_b6c031a57087af131ed0176e17c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d22a493bc593e66d2ae67d9db2" ON "email_queue" ("emailType") `);
        await queryRunner.query(`CREATE INDEX "IDX_f855e2753daf148492d2d54e66" ON "email_queue" ("recipientEmail") `);
        await queryRunner.query(`CREATE INDEX "IDX_69b1fa82c6e86826bdff3d95bb" ON "email_queue" ("scheduledFor") `);
        await queryRunner.query(`CREATE INDEX "IDX_a76f5b26939dccacf5601038ce" ON "email_queue" ("status") `);
        await queryRunner.query(`CREATE TABLE "email_logs" ("id" SERIAL NOT NULL, "emailQueueId" integer NOT NULL, "recipientEmail" character varying(255) NOT NULL, "delivered" boolean NOT NULL DEFAULT false, "deliveredAt" TIMESTAMP, "opened" boolean NOT NULL DEFAULT false, "firstOpenedAt" TIMESTAMP, "lastOpenedAt" TIMESTAMP, "openCount" integer NOT NULL DEFAULT '0', "clicked" boolean NOT NULL DEFAULT false, "firstClickedAt" TIMESTAMP, "lastClickedAt" TIMESTAMP, "clickCount" integer NOT NULL DEFAULT '0', "bounced" boolean NOT NULL DEFAULT false, "bounceType" character varying(20), "bounceReason" text, "bouncedAt" TIMESTAMP, "markedAsSpam" boolean NOT NULL DEFAULT false, "markedAsSpamAt" TIMESTAMP, "unsubscribed" boolean NOT NULL DEFAULT false, "unsubscribedAt" TIMESTAMP, "webhookEvents" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8ce1a978cad79a5577f40062766" UNIQUE ("emailQueueId"), CONSTRAINT "REL_8ce1a978cad79a5577f4006276" UNIQUE ("emailQueueId"), CONSTRAINT "PK_999382218924e953a790d340571" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a864d5f15f0d39e23e51ab1668" ON "email_logs" ("clicked") `);
        await queryRunner.query(`CREATE INDEX "IDX_bc9c3d78c9d7fc08f6a46d215d" ON "email_logs" ("opened") `);
        await queryRunner.query(`CREATE INDEX "IDX_8a71246d08b55f06ee78ca1165" ON "email_logs" ("recipientEmail") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8ce1a978cad79a5577f4006276" ON "email_logs" ("emailQueueId") `);
        await queryRunner.query(`CREATE TYPE "public"."stock_reservations_status_enum" AS ENUM('pending', 'fulfilled', 'released', 'expired')`);
        await queryRunner.query(`CREATE TABLE "stock_reservations" ("id" SERIAL NOT NULL, "variantId" integer NOT NULL, "quantity" integer NOT NULL, "status" "public"."stock_reservations_status_enum" NOT NULL DEFAULT 'pending', "cartId" integer, "cartItemId" integer, "orderId" integer, "userId" integer, "sessionId" character varying(255), "expiresAt" TIMESTAMP NOT NULL, "fulfilledAt" TIMESTAMP, "releasedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_46ec0f5605d70f64654ad4e7bd9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_5bb5d01e006628288129347c7d" ON "stock_reservations" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_7a419986b1189abd6a4c618360" ON "stock_reservations" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_677b1454815d99332509a6a8f0" ON "stock_reservations" ("cartId") `);
        await queryRunner.query(`CREATE INDEX "IDX_3bf3bb86a01d66974f9b508d5c" ON "stock_reservations" ("expiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_1425e71cee4dea937412159195" ON "stock_reservations" ("variantId", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."inventory_logs_type_enum" AS ENUM('sale', 'return', 'restock', 'adjustment', 'damaged', 'lost', 'reservation', 'release')`);
        await queryRunner.query(`CREATE TABLE "inventory_logs" ("id" SERIAL NOT NULL, "productId" integer NOT NULL, "variantId" integer NOT NULL, "type" "public"."inventory_logs_type_enum" NOT NULL, "quantityChange" integer NOT NULL, "quantityBefore" integer NOT NULL, "quantityAfter" integer NOT NULL, "orderId" integer, "orderItemId" integer, "performedBy" integer, "reason" text, "metadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_06b444680ab11eb7c7d0ed6eced" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_b68a981e6d8069e517c4cefa80" ON "inventory_logs" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_bea4a904d9b0c9e6157355856c" ON "inventory_logs" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_b83dc97b270782a016d4ee00ed" ON "inventory_logs" ("productId", "variantId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "customer_profiles" ("id" SERIAL NOT NULL, "userId" integer, "email" character varying(255) NOT NULL, "fullName" character varying(255), "phone" character varying(20), "isRegistered" boolean NOT NULL DEFAULT false, "firstOrderAt" TIMESTAMP, "lastOrderAt" TIMESTAMP, "orderCount" integer NOT NULL DEFAULT '0', "totalSpent" numeric(15,2) NOT NULL DEFAULT '0', "averageOrderValue" numeric(15,2) NOT NULL DEFAULT '0', "lifetimeValue" numeric(15,2) NOT NULL DEFAULT '0', "marketingPreferences" jsonb, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_5b534069c56790acd59665798c3" UNIQUE ("userId"), CONSTRAINT "REL_5b534069c56790acd59665798c" UNIQUE ("userId"), CONSTRAINT "PK_ece08ee55cbe707d9f870907727" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d9f08fe93e623b0ebf557d3f7f" ON "customer_profiles" ("createdAt") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5b534069c56790acd59665798c" ON "customer_profiles" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d93fd87b39947e5611aecc160f" ON "customer_profiles" ("email") `);
        await queryRunner.query(`CREATE TABLE "addresses" ("id" SERIAL NOT NULL, "customerProfileId" integer NOT NULL, "addressType" character varying(20) NOT NULL DEFAULT 'SHIPPING', "fullName" character varying(255) NOT NULL, "phone" character varying(20) NOT NULL, "addressLine1" text NOT NULL, "addressLine2" text, "city" character varying(100) NOT NULL, "state" character varying(100) NOT NULL, "postalCode" character varying(20), "countryCode" character varying(2) NOT NULL DEFAULT 'NG', "isPrimary" boolean NOT NULL DEFAULT false, "label" character varying(50), "deliveryNotes" text, "latitude" numeric(10,8), "longitude" numeric(11,8), "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_745d8f43d3af10ab8247465e450" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1d330f492f2c7cde2746739ae8" ON "addresses" ("isPrimary") `);
        await queryRunner.query(`CREATE INDEX "IDX_ff6cf09b9b991d187c417bacc9" ON "addresses" ("customerProfileId") `);
        await queryRunner.query(`CREATE TYPE "public"."coupons_coupontype_enum" AS ENUM('percentage', 'fixed_amount', 'free_shipping', 'buy_x_get_y')`);
        await queryRunner.query(`CREATE TYPE "public"."coupons_status_enum" AS ENUM('active', 'inactive', 'expired', 'depleted')`);
        await queryRunner.query(`CREATE TABLE "coupons" ("id" SERIAL NOT NULL, "businessId" integer NOT NULL, "code" character varying(50) NOT NULL, "name" character varying(255) NOT NULL, "couponType" "public"."coupons_coupontype_enum" NOT NULL, "discountValue" numeric(10,2) NOT NULL, "status" "public"."coupons_status_enum" NOT NULL DEFAULT 'active', "minPurchaseAmount" numeric(10,2), "maxDiscountAmount" numeric(10,2), "totalUsageLimit" integer, "perCustomerLimit" integer, "usageCount" integer NOT NULL DEFAULT '0', "validFrom" TIMESTAMP, "validUntil" TIMESTAMP, "applicableProductIds" jsonb, "applicableCategoryIds" jsonb, "excludedProductIds" jsonb, "firstOrderOnly" boolean NOT NULL DEFAULT false, "stackable" boolean NOT NULL DEFAULT false, "createdBy" integer, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_e025109230e82925843f2a14c48" UNIQUE ("code"), CONSTRAINT "PK_d7ea8864a0150183770f3e9a8cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_349c54aae3ee81ede487f2098e" ON "coupons" ("validFrom", "validUntil") `);
        await queryRunner.query(`CREATE INDEX "IDX_ed793a952de93a5f8d5dfdace5" ON "coupons" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e025109230e82925843f2a14c4" ON "coupons" ("code") `);
        await queryRunner.query(`CREATE INDEX "IDX_22a92591950d9cb88e8163ceca" ON "coupons" ("businessId") `);
        await queryRunner.query(`CREATE TABLE "coupon_usage" ("id" SERIAL NOT NULL, "couponId" integer NOT NULL, "orderId" integer NOT NULL, "userId" integer, "customerEmail" character varying(255) NOT NULL, "orderSubtotal" numeric(10,2) NOT NULL, "discountAmount" numeric(10,2) NOT NULL, "orderTotal" numeric(10,2) NOT NULL, "customerIp" character varying(45), "wasFirstOrder" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5727b2e426ee3e63c3f5e200e61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8ebde2e3f11a0b3747a7c51dfe" ON "coupon_usage" ("customerEmail") `);
        await queryRunner.query(`CREATE INDEX "IDX_302670923e49b67d7f4e9772f6" ON "coupon_usage" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_98cbb4d3b3fec527d608058eb8" ON "coupon_usage" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_26a0738a539db72546019ae130" ON "coupon_usage" ("couponId", "createdAt") `);
        await queryRunner.query(`CREATE TABLE "carts" ("id" SERIAL NOT NULL, "userId" integer, "sessionId" character varying(255), "status" character varying(20) NOT NULL DEFAULT 'ACTIVE', "subtotal" numeric(15,2) NOT NULL DEFAULT '0', "itemCount" integer NOT NULL DEFAULT '0', "couponCode" character varying(50), "discountAmount" numeric(10,2) NOT NULL DEFAULT '0', "currency" character varying(3) NOT NULL DEFAULT 'NGN', "customerIp" character varying(45), "customerUserAgent" text, "convertedToOrderId" integer, "abandonedAt" TIMESTAMP, "convertedAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_69828a178f152f157dcf2f70a89" UNIQUE ("userId"), CONSTRAINT "PK_b5f695a59f5ebb50af3c8160816" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c19f7859d0ead8c988590e9f61" ON "carts" ("updatedAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_08c5fb75dc0c2ed434aac2b0f5" ON "carts" ("sessionId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_69828a178f152f157dcf2f70a8" ON "carts" ("userId") `);
        await queryRunner.query(`CREATE TABLE "cart_items" ("id" SERIAL NOT NULL, "cartId" integer NOT NULL, "productId" integer NOT NULL, "variantId" integer NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "unitPrice" numeric(10,2) NOT NULL, "subtotal" numeric(10,2) NOT NULL, "productName" character varying(255) NOT NULL, "variantName" character varying(255), "imageUrl" text, "stockReservationId" integer, "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6fccf5ec03c172d27a28a82928b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_72679d98b31c737937b8932ebe" ON "cart_items" ("productId") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_b6efb56bc53b16c85d8c987e62" ON "cart_items" ("cartId", "variantId") `);
        await queryRunner.query(`CREATE TABLE "cart_abandonments" ("id" SERIAL NOT NULL, "cartId" integer NOT NULL, "status" character varying(30) NOT NULL DEFAULT 'IDENTIFIED', "customerEmail" character varying(255), "cartValue" numeric(15,2) NOT NULL DEFAULT '0', "itemCount" integer NOT NULL DEFAULT '0', "firstReminderSentAt" TIMESTAMP, "secondReminderSentAt" TIMESTAMP, "thirdReminderSentAt" TIMESTAMP, "nextReminderAt" TIMESTAMP, "isRecovered" boolean NOT NULL DEFAULT false, "recoveredAt" TIMESTAMP, "recoveredOrderId" integer, "recoveryDiscountCode" character varying(50), "campaignMetadata" jsonb, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_5bd49fdaf30edadf0fb1004f8e6" UNIQUE ("cartId"), CONSTRAINT "REL_5bd49fdaf30edadf0fb1004f8e" UNIQUE ("cartId"), CONSTRAINT "PK_12865a214882a79ead69d3bb0c9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e1975287515751c6c8fe58590e" ON "cart_abandonments" ("nextReminderAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_c52a919a7c17d269bd6f61754b" ON "cart_abandonments" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_5bd49fdaf30edadf0fb1004f8e" ON "cart_abandonments" ("cartId") `);
        await queryRunner.query(`ALTER TABLE "traffic_events" ADD CONSTRAINT "FK_ebd75e4b14dc54e168d0b48dd1e" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_profiles" ADD CONSTRAINT "FK_8481388d6325e752cd4d7e26c6d" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_kyc" ADD CONSTRAINT "FK_4e246b1a648a4bf051e4d082eb5" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_security" ADD CONSTRAINT "FK_2c6ad367fcb763798ea480097b1" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_onboarding" ADD CONSTRAINT "FK_f3e7bb4005372c40076e8af93ca" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "wallets" ADD CONSTRAINT "FK_2ecdb33f23e9a6fc392025c0b97" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bank_accounts" ADD CONSTRAINT "FK_45ef3ca170943e2c70e8073a7c5" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_368e146b785b574f42ae9e53d5e" FOREIGN KEY ("roleId") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_78725ac7117e7526e028014606b" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leads" ADD CONSTRAINT "FK_08e50b251ecb4417800af268b26" FOREIGN KEY ("formId") REFERENCES "lead-forms"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "leads" ADD CONSTRAINT "FK_daf8eb3d52d018ea43df6d5edab" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lead-forms" ADD CONSTRAINT "FK_67809c78e9c1f5974410eca85c2" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "lead-forms" ADD CONSTRAINT "FK_348e4860ecf98016ea9636ce6c0" FOREIGN KEY ("createdBy") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_payment_accounts" ADD CONSTRAINT "FK_2bccc958611f57d6dcd621a733c" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_payment_accounts" ADD CONSTRAINT "FK_1706d0af8f5b8e47bccd7cd8533" FOREIGN KEY ("settlementBankAccountId") REFERENCES "bank_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_settlement_configs" ADD CONSTRAINT "FK_99beea24e18ed0b25f0203db191" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "business_settlement_configs" ADD CONSTRAINT "FK_d854a31f9b48ea4a47d230254d6" FOREIGN KEY ("defaultBankAccountId") REFERENCES "bank_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_sizes" ADD CONSTRAINT "FK_699f5366c2ebf46a77589bd225e" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_f515690c571a03400a9876600b5" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_images" ADD CONSTRAINT "FK_b367708bf720c8dd62fc6833161" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_99d90c2a483d79f3b627fb1d5e9" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_359bd8406fbfb50e3ea42b5631f" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "products" ADD CONSTRAINT "FK_ff56834e735fa78a15d0cf21926" FOREIGN KEY ("categoryId") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_cdb99c05982d5191ac8465ac010" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_516736b9807228bb17b2d0a3e2a" FOREIGN KEY ("variantId") REFERENCES "product_variants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_status_history" ADD CONSTRAINT "FK_689db3835e5550e68d26ca32676" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_payments" ADD CONSTRAINT "FK_abca480893311e20150f01b2f15" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_shipments" ADD CONSTRAINT "FK_fde014e470812e0510240623951" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_refunds" ADD CONSTRAINT "FK_1d266acc6f94a5d28bf7bfa1691" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "FK_778777c5d7d56ed1bbaa907b8e5" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settlements" ADD CONSTRAINT "FK_27caeda90ab187dfdbb68a4b6d7" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settlements" ADD CONSTRAINT "FK_688cf34e61f3b2dc58a1fa91f2b" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "settlements" ADD CONSTRAINT "FK_11d250a420bfe4c0a1f1cf4e079" FOREIGN KEY ("bankAccountId") REFERENCES "bank_accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "businesses" ADD CONSTRAINT "FK_01845bacd013698b8bffb920933" FOREIGN KEY ("businessTypeId") REFERENCES "business_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "businesses" ADD CONSTRAINT "FK_5ba6375fdc72387a2d2d0bb7720" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_a8bd8d95914d6228770fe87b8a3" FOREIGN KEY ("performedBy") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "otps" ADD CONSTRAINT "FK_82b0deb105275568cdcef2823eb" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_progress" ADD CONSTRAINT "FK_b5d0e1b57bc6c761fb49e79bf89" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_6bb58f2b6e30cb51a6504599f41" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_9f24c9c8611e077a48a0645e3df" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "transactions" ADD CONSTRAINT "FK_2fdbbae70ff802bc8b703ee7c5c" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_7ed5659e7139fc8bc039198cc1f" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_d17ce9c119d29c7ec8c884044cb" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_a6b3c434392f5d10ec171043666" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_53a68dc905777554b7f702791fa" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_1e6c554d615dd5a5bf0e11ee0e9" FOREIGN KEY ("orderItemId") REFERENCES "order_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "email_logs" ADD CONSTRAINT "FK_8ce1a978cad79a5577f40062766" FOREIGN KEY ("emailQueueId") REFERENCES "email_queue"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "stock_reservations" ADD CONSTRAINT "FK_9db9f46b85339dae1a4a5fb61e9" FOREIGN KEY ("variantId") REFERENCES "product_variants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_logs" ADD CONSTRAINT "FK_14dbb38878c6ae69c4774bcb272" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "inventory_logs" ADD CONSTRAINT "FK_9843e02a295c020f7d70b6f6705" FOREIGN KEY ("variantId") REFERENCES "product_variants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "customer_profiles" ADD CONSTRAINT "FK_5b534069c56790acd59665798c3" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD CONSTRAINT "FK_ff6cf09b9b991d187c417bacc93" FOREIGN KEY ("customerProfileId") REFERENCES "customer_profiles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupons" ADD CONSTRAINT "FK_22a92591950d9cb88e8163ceca6" FOREIGN KEY ("businessId") REFERENCES "businesses"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupon_usage" ADD CONSTRAINT "FK_18b10b5df91ce11abe764e6edda" FOREIGN KEY ("couponId") REFERENCES "coupons"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupon_usage" ADD CONSTRAINT "FK_98cbb4d3b3fec527d608058eb80" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "coupon_usage" ADD CONSTRAINT "FK_302670923e49b67d7f4e9772f64" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carts" ADD CONSTRAINT "FK_69828a178f152f157dcf2f70a89" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_edd714311619a5ad09525045838" FOREIGN KEY ("cartId") REFERENCES "carts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_72679d98b31c737937b8932ebe6" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_items" ADD CONSTRAINT "FK_5a27845bc2d79be6f1fa3d2c036" FOREIGN KEY ("variantId") REFERENCES "product_variants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cart_abandonments" ADD CONSTRAINT "FK_5bd49fdaf30edadf0fb1004f8e6" FOREIGN KEY ("cartId") REFERENCES "carts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "cart_abandonments" DROP CONSTRAINT "FK_5bd49fdaf30edadf0fb1004f8e6"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_5a27845bc2d79be6f1fa3d2c036"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_72679d98b31c737937b8932ebe6"`);
        await queryRunner.query(`ALTER TABLE "cart_items" DROP CONSTRAINT "FK_edd714311619a5ad09525045838"`);
        await queryRunner.query(`ALTER TABLE "carts" DROP CONSTRAINT "FK_69828a178f152f157dcf2f70a89"`);
        await queryRunner.query(`ALTER TABLE "coupon_usage" DROP CONSTRAINT "FK_302670923e49b67d7f4e9772f64"`);
        await queryRunner.query(`ALTER TABLE "coupon_usage" DROP CONSTRAINT "FK_98cbb4d3b3fec527d608058eb80"`);
        await queryRunner.query(`ALTER TABLE "coupon_usage" DROP CONSTRAINT "FK_18b10b5df91ce11abe764e6edda"`);
        await queryRunner.query(`ALTER TABLE "coupons" DROP CONSTRAINT "FK_22a92591950d9cb88e8163ceca6"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP CONSTRAINT "FK_ff6cf09b9b991d187c417bacc93"`);
        await queryRunner.query(`ALTER TABLE "customer_profiles" DROP CONSTRAINT "FK_5b534069c56790acd59665798c3"`);
        await queryRunner.query(`ALTER TABLE "inventory_logs" DROP CONSTRAINT "FK_9843e02a295c020f7d70b6f6705"`);
        await queryRunner.query(`ALTER TABLE "inventory_logs" DROP CONSTRAINT "FK_14dbb38878c6ae69c4774bcb272"`);
        await queryRunner.query(`ALTER TABLE "stock_reservations" DROP CONSTRAINT "FK_9db9f46b85339dae1a4a5fb61e9"`);
        await queryRunner.query(`ALTER TABLE "email_logs" DROP CONSTRAINT "FK_8ce1a978cad79a5577f40062766"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_1e6c554d615dd5a5bf0e11ee0e9"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_53a68dc905777554b7f702791fa"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_a6b3c434392f5d10ec171043666"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_d17ce9c119d29c7ec8c884044cb"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_7ed5659e7139fc8bc039198cc1f"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_2fdbbae70ff802bc8b703ee7c5c"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_9f24c9c8611e077a48a0645e3df"`);
        await queryRunner.query(`ALTER TABLE "transactions" DROP CONSTRAINT "FK_6bb58f2b6e30cb51a6504599f41"`);
        await queryRunner.query(`ALTER TABLE "user_progress" DROP CONSTRAINT "FK_b5d0e1b57bc6c761fb49e79bf89"`);
        await queryRunner.query(`ALTER TABLE "otps" DROP CONSTRAINT "FK_82b0deb105275568cdcef2823eb"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_a8bd8d95914d6228770fe87b8a3"`);
        await queryRunner.query(`ALTER TABLE "businesses" DROP CONSTRAINT "FK_5ba6375fdc72387a2d2d0bb7720"`);
        await queryRunner.query(`ALTER TABLE "businesses" DROP CONSTRAINT "FK_01845bacd013698b8bffb920933"`);
        await queryRunner.query(`ALTER TABLE "settlements" DROP CONSTRAINT "FK_11d250a420bfe4c0a1f1cf4e079"`);
        await queryRunner.query(`ALTER TABLE "settlements" DROP CONSTRAINT "FK_688cf34e61f3b2dc58a1fa91f2b"`);
        await queryRunner.query(`ALTER TABLE "settlements" DROP CONSTRAINT "FK_27caeda90ab187dfdbb68a4b6d7"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_778777c5d7d56ed1bbaa907b8e5"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "FK_151b79a83ba240b0cb31b2302d1"`);
        await queryRunner.query(`ALTER TABLE "order_refunds" DROP CONSTRAINT "FK_1d266acc6f94a5d28bf7bfa1691"`);
        await queryRunner.query(`ALTER TABLE "order_shipments" DROP CONSTRAINT "FK_fde014e470812e0510240623951"`);
        await queryRunner.query(`ALTER TABLE "order_payments" DROP CONSTRAINT "FK_abca480893311e20150f01b2f15"`);
        await queryRunner.query(`ALTER TABLE "order_status_history" DROP CONSTRAINT "FK_689db3835e5550e68d26ca32676"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_516736b9807228bb17b2d0a3e2a"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_cdb99c05982d5191ac8465ac010"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_ff56834e735fa78a15d0cf21926"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_359bd8406fbfb50e3ea42b5631f"`);
        await queryRunner.query(`ALTER TABLE "products" DROP CONSTRAINT "FK_99d90c2a483d79f3b627fb1d5e9"`);
        await queryRunner.query(`ALTER TABLE "product_images" DROP CONSTRAINT "FK_b367708bf720c8dd62fc6833161"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_f515690c571a03400a9876600b5"`);
        await queryRunner.query(`ALTER TABLE "product_sizes" DROP CONSTRAINT "FK_699f5366c2ebf46a77589bd225e"`);
        await queryRunner.query(`ALTER TABLE "business_settlement_configs" DROP CONSTRAINT "FK_d854a31f9b48ea4a47d230254d6"`);
        await queryRunner.query(`ALTER TABLE "business_settlement_configs" DROP CONSTRAINT "FK_99beea24e18ed0b25f0203db191"`);
        await queryRunner.query(`ALTER TABLE "business_payment_accounts" DROP CONSTRAINT "FK_1706d0af8f5b8e47bccd7cd8533"`);
        await queryRunner.query(`ALTER TABLE "business_payment_accounts" DROP CONSTRAINT "FK_2bccc958611f57d6dcd621a733c"`);
        await queryRunner.query(`ALTER TABLE "lead-forms" DROP CONSTRAINT "FK_348e4860ecf98016ea9636ce6c0"`);
        await queryRunner.query(`ALTER TABLE "lead-forms" DROP CONSTRAINT "FK_67809c78e9c1f5974410eca85c2"`);
        await queryRunner.query(`ALTER TABLE "leads" DROP CONSTRAINT "FK_daf8eb3d52d018ea43df6d5edab"`);
        await queryRunner.query(`ALTER TABLE "leads" DROP CONSTRAINT "FK_08e50b251ecb4417800af268b26"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_78725ac7117e7526e028014606b"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_368e146b785b574f42ae9e53d5e"`);
        await queryRunner.query(`ALTER TABLE "bank_accounts" DROP CONSTRAINT "FK_45ef3ca170943e2c70e8073a7c5"`);
        await queryRunner.query(`ALTER TABLE "wallets" DROP CONSTRAINT "FK_2ecdb33f23e9a6fc392025c0b97"`);
        await queryRunner.query(`ALTER TABLE "user_onboarding" DROP CONSTRAINT "FK_f3e7bb4005372c40076e8af93ca"`);
        await queryRunner.query(`ALTER TABLE "user_security" DROP CONSTRAINT "FK_2c6ad367fcb763798ea480097b1"`);
        await queryRunner.query(`ALTER TABLE "user_kyc" DROP CONSTRAINT "FK_4e246b1a648a4bf051e4d082eb5"`);
        await queryRunner.query(`ALTER TABLE "user_profiles" DROP CONSTRAINT "FK_8481388d6325e752cd4d7e26c6d"`);
        await queryRunner.query(`ALTER TABLE "traffic_events" DROP CONSTRAINT "FK_ebd75e4b14dc54e168d0b48dd1e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5bd49fdaf30edadf0fb1004f8e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c52a919a7c17d269bd6f61754b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e1975287515751c6c8fe58590e"`);
        await queryRunner.query(`DROP TABLE "cart_abandonments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b6efb56bc53b16c85d8c987e62"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_72679d98b31c737937b8932ebe"`);
        await queryRunner.query(`DROP TABLE "cart_items"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_69828a178f152f157dcf2f70a8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_08c5fb75dc0c2ed434aac2b0f5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c19f7859d0ead8c988590e9f61"`);
        await queryRunner.query(`DROP TABLE "carts"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26a0738a539db72546019ae130"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_98cbb4d3b3fec527d608058eb8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_302670923e49b67d7f4e9772f6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ebde2e3f11a0b3747a7c51dfe"`);
        await queryRunner.query(`DROP TABLE "coupon_usage"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_22a92591950d9cb88e8163ceca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e025109230e82925843f2a14c4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ed793a952de93a5f8d5dfdace5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_349c54aae3ee81ede487f2098e"`);
        await queryRunner.query(`DROP TABLE "coupons"`);
        await queryRunner.query(`DROP TYPE "public"."coupons_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."coupons_coupontype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff6cf09b9b991d187c417bacc9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1d330f492f2c7cde2746739ae8"`);
        await queryRunner.query(`DROP TABLE "addresses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d93fd87b39947e5611aecc160f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5b534069c56790acd59665798c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d9f08fe93e623b0ebf557d3f7f"`);
        await queryRunner.query(`DROP TABLE "customer_profiles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b83dc97b270782a016d4ee00ed"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bea4a904d9b0c9e6157355856c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b68a981e6d8069e517c4cefa80"`);
        await queryRunner.query(`DROP TABLE "inventory_logs"`);
        await queryRunner.query(`DROP TYPE "public"."inventory_logs_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1425e71cee4dea937412159195"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3bf3bb86a01d66974f9b508d5c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_677b1454815d99332509a6a8f0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7a419986b1189abd6a4c618360"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5bb5d01e006628288129347c7d"`);
        await queryRunner.query(`DROP TABLE "stock_reservations"`);
        await queryRunner.query(`DROP TYPE "public"."stock_reservations_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ce1a978cad79a5577f4006276"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8a71246d08b55f06ee78ca1165"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bc9c3d78c9d7fc08f6a46d215d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a864d5f15f0d39e23e51ab1668"`);
        await queryRunner.query(`DROP TABLE "email_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a76f5b26939dccacf5601038ce"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_69b1fa82c6e86826bdff3d95bb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f855e2753daf148492d2d54e66"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d22a493bc593e66d2ae67d9db2"`);
        await queryRunner.query(`DROP TABLE "email_queue"`);
        await queryRunner.query(`DROP TYPE "public"."email_queue_provider_enum"`);
        await queryRunner.query(`DROP TYPE "public"."email_queue_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."email_queue_emailtype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1e6c554d615dd5a5bf0e11ee0e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_53a68dc905777554b7f702791f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a6b3c434392f5d10ec17104366"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d17ce9c119d29c7ec8c884044c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_058c6448644b27a8e63fd03106"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7ed5659e7139fc8bc039198cc1"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85d65d236f62b4496cd115f097"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e744417ceb0b530285c08f3865"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_da87c55b3bbbe96c6ed88ea7ee"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2d5fa024a84dceb158b2b95f34"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2fdbbae70ff802bc8b703ee7c5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9f24c9c8611e077a48a0645e3d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6bb58f2b6e30cb51a6504599f4"`);
        await queryRunner.query(`DROP TABLE "transactions"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_flow_enum"`);
        await queryRunner.query(`DROP TYPE "public"."transactions_type_enum"`);
        await queryRunner.query(`DROP TABLE "user_progress"`);
        await queryRunner.query(`DROP TYPE "public"."user_progress_event_enum"`);
        await queryRunner.query(`DROP TABLE "otps"`);
        await queryRunner.query(`DROP TYPE "public"."otps_purpose_enum"`);
        await queryRunner.query(`DROP TYPE "public"."otps_otptype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2ea511240853f023d2219bc661"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_06a528c9ad99e80e86baf8fa44"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_05e9f830e250583c68cfe3a5aa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c4c8f6c19ceb46ad1279b75fcc"`);
        await queryRunner.query(`DROP TABLE "system_events"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13c69424c440a0e765053feb4b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a8bd8d95914d6228770fe87b8a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c69efb19bf127c97e6740ad530"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ddc86298ac7fadad468b28d83"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_business_storeName"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_business_slug"`);
        await queryRunner.query(`DROP TABLE "businesses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7e1995ebbedd550e18c457548b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_688cf34e61f3b2dc58a1fa91f2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_483cc42916e1d0847b3fb08092"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_86077b8251cb7c44bb836a314e"`);
        await queryRunner.query(`DROP TABLE "settlements"`);
        await queryRunner.query(`DROP TYPE "public"."settlements_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5025e0259ec0b1ffb5f0ea6685"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f4b9818a08b822a31493fdee9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19a7638af058ba9a727b100869"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_775c9f06fc27ae3ff8fb26f2c4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_01b20118a3f640214e7a8a6b29"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19a7638af058ba9a727b100869"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_778777c5d7d56ed1bbaa907b8e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_151b79a83ba240b0cb31b2302d"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TYPE "public"."orders_deliverymethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_paymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_paymentstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1d266acc6f94a5d28bf7bfa169"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fc74256b145a0f94ef592d3776"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26ba92d70706a998979a107c46"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_abde04a1ead8cce748c0c9c6e0"`);
        await queryRunner.query(`DROP TABLE "order_refunds"`);
        await queryRunner.query(`DROP TYPE "public"."order_refunds_reason_enum"`);
        await queryRunner.query(`DROP TYPE "public"."order_refunds_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."order_refunds_refundmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."order_refunds_refundtype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fde014e470812e051024062395"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_19d9c6672e6f155f97257c34a8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fb7744b02af865e1cf3d329482"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cead94ae651bf71a9ac18199d1"`);
        await queryRunner.query(`DROP TABLE "order_shipments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_abca480893311e20150f01b2f1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_11dec6a1b92ef13a86992f0522"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b0a057dbf38cec095c3113622a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fbc1adaaa870de1aae3da1903c"`);
        await queryRunner.query(`DROP TABLE "order_payments"`);
        await queryRunner.query(`DROP TYPE "public"."order_payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."order_payments_paymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."order_payments_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_be366be57f21391e49f42e0b18"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_41a834150f6ba631f6e9e6f13c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a025fc2421d2553fb5aaaa77dc"`);
        await queryRunner.query(`DROP TABLE "order_status_history"`);
        await queryRunner.query(`DROP TYPE "public"."order_status_history_previousstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."order_status_history_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f421c8981cca05954f98667134"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_516736b9807228bb17b2d0a3e2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cdb99c05982d5191ac8465ac01"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1d359a55923bb45b057fbdab0"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP TYPE "public"."order_items_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_69e49df9a08f8ded911758822f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_63fcb3d8806a6efd53dbc67430"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0591b4a1abb428c6d86744cc0a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_75895eeb1903f8a17816dafe0a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ff56834e735fa78a15d0cf2192"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4c9fb58de893725258746385e1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_359bd8406fbfb50e3ea42b5631"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99d90c2a483d79f3b627fb1d5e"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a47d8b28fa544e88fb805b3b33"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0e608cfeddd2708513ff81b73d"`);
        await queryRunner.query(`DROP TABLE "product_images"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_96473e185ba3f4f12dd0b2734d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_46f236f21640f9da218a063a86"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cb151f7020703dd7b20656b7bb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_74f84d49e67995a1e46c402eab"`);
        await queryRunner.query(`DROP TABLE "product_variants"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8b0be371d28245da6e4f4b6187"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "product_sizes"`);
        await queryRunner.query(`DROP TYPE "public"."product_sizes_measurement_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_99beea24e18ed0b25f0203db19"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3315c15893281839b388c327b5"`);
        await queryRunner.query(`DROP TABLE "business_settlement_configs"`);
        await queryRunner.query(`DROP TYPE "public"."business_settlement_configs_schedule_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2bccc958611f57d6dcd621a733"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fc1905d33f79be3fd5c3049985"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_85d276b69bd948f6722e85e5b6"`);
        await queryRunner.query(`DROP TABLE "business_payment_accounts"`);
        await queryRunner.query(`DROP TYPE "public"."business_payment_accounts_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."business_payment_accounts_provider_enum"`);
        await queryRunner.query(`DROP TABLE "lead-forms"`);
        await queryRunner.query(`DROP TABLE "leads"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."users_usertype_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_40666d1bcf2deba09f1f415293"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f048bcb5cb3c77a3d765ebc3c1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9dcc47dcf41085bb47109de56e"`);
        await queryRunner.query(`DROP TABLE "bank_accounts"`);
        await queryRunner.query(`DROP TYPE "public"."bank_accounts_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2ecdb33f23e9a6fc392025c0b9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_444a7f9feac3d2154c45875d0a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_79e9c3c76ea89e2334986f1e32"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e83ee448888683883666ce553e"`);
        await queryRunner.query(`DROP TABLE "wallets"`);
        await queryRunner.query(`DROP TYPE "public"."wallets_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."wallets_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f3e7bb4005372c40076e8af93c"`);
        await queryRunner.query(`DROP TABLE "user_onboarding"`);
        await queryRunner.query(`DROP TYPE "public"."user_onboarding_currentstep_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2c6ad367fcb763798ea480097b"`);
        await queryRunner.query(`DROP TABLE "user_security"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e246b1a648a4bf051e4d082eb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_eaeb0d7330ff6e5c87d4f9d628"`);
        await queryRunner.query(`DROP TABLE "user_kyc"`);
        await queryRunner.query(`DROP TYPE "public"."user_kyc_verificationprovider_enum"`);
        await queryRunner.query(`DROP TYPE "public"."user_kyc_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8481388d6325e752cd4d7e26c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dceea64a755bbbc3b64f0ec018"`);
        await queryRunner.query(`DROP TABLE "user_profiles"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TYPE "public"."roles_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."roles_usertype_enum"`);
        await queryRunner.query(`DROP TABLE "business_types"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TRAFFIC_BUSINESS_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TRAFFIC_CREATED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TRAFFIC_BUSINESS_CREATED"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TRAFFIC_BUSINESS_SOURCE"`);
        await queryRunner.query(`DROP TABLE "traffic_events"`);
        await queryRunner.query(`DROP TYPE "public"."traffic_events_source_enum"`);
    }

}
