
// src/dashboard/dto/dashboard-response.dto.ts

import { ApiProperty } from '@nestjs/swagger';
import { IsOptional, IsEnum, IsDateString } from 'class-validator';
import { Type } from 'class-transformer';


export class TrafficSourceMetric {
  @ApiProperty({ description: 'Traffic source name', example: 'DIRECT' })
  source: string;

  @ApiProperty({ description: 'Number of visits from this source', example: 450 })
  count: number;

  @ApiProperty({ description: 'Percentage of total traffic', example: 36.0 })
  percentage: number;
}


export class LandingPageMetric {
  @ApiProperty({ description: 'Landing page URL', example: '/products/electronics' })
  page: string;

  @ApiProperty({ description: 'Number of visits to this page', example: 230 })
  visits: number;
}

export class RecentOrderDto {
  @ApiProperty({ description: 'Order ID', example: 1523 })
  id: number;

  @ApiProperty({ description: 'Order reference number', example: 'ORD-A3B4C5D6' })
  orderReference: string;

  @ApiProperty({ description: 'Customer full name', example: 'John Doe' })
  customerName: string;

  @ApiProperty({ description: 'Total order amount', example: 15750.00 })
  total: number;

  @ApiProperty({ description: 'Order status', example: 'COMPLETED' })
  status: string;

  @ApiProperty({ description: 'Payment status', example: 'PAID' })
  paymentStatus: string;

  @ApiProperty({ description: 'Order creation date', example: '2024-12-20T14:30:00.000Z' })
  createdAt: Date;
}

export class TopProductDto {
  @ApiProperty({ description: 'Product ID', example: 45 })
  id: number;

  @ApiProperty({ description: 'Product name', example: 'Wireless Bluetooth Headphones' })
  name: string;

  @ApiProperty({ description: 'Product price', example: 8500.00 })
  price: number;

  @ApiProperty({ description: 'Current stock quantity', example: 25 })
  quantityInStock: number;

  @ApiProperty({ description: 'Total number of orders for this product', example: 48 })
  totalOrders: number;

  @ApiProperty({ description: 'Total revenue generated by this product', example: 408000.00 })
  revenue: number;

  @ApiProperty({ description: 'Product image URLs', type: [String], example: ['https://example.com/image1.jpg'] })
  images: string[];
}

export class SalesChartDataDto {
  @ApiProperty({ description: 'Date in ISO format', example: '2024-12-15' })
  date: string;

  @ApiProperty({ description: 'Number of orders on this date', example: 12 })
  orders: number;

  @ApiProperty({ description: 'Total revenue on this date', example: 45600.50 })
  revenue: number;
}

export class OrderStatusDistributionDto {
  @ApiProperty({ description: 'Order status', example: 'COMPLETED' })
  status: string;

  @ApiProperty({ description: 'Number of orders with this status', example: 100 })
  count: number;

  @ApiProperty({ description: 'Percentage of total orders', example: 66.67 })
  percentage: number;
}

export class PaymentMethodDistributionDto {
  @ApiProperty({ description: 'Payment method', example: 'CARD' })
  method: string;

  @ApiProperty({ description: 'Number of orders using this method', example: 120 })
  count: number;

  @ApiProperty({ description: 'Total amount paid via this method', example: 98500.00 })
  amount: number;

  @ApiProperty({ description: 'Percentage of total orders', example: 80.0 })
  percentage: number;
}

export class DashboardQueryDto {
  @ApiProperty({ description: 'Start date for data filtering', required: false, example: '2024-01-01T00:00:00.000Z' })
  @IsOptional()
  @IsDateString()
  @Type(() => Date)
  startDate?: Date;

  @ApiProperty({ description: 'End date for data filtering', required: false, example: '2024-12-31T23:59:59.999Z' })
  @IsOptional()
  @IsDateString()
  @Type(() => Date)
  endDate?: Date;

  @ApiProperty({
    description: 'Predefined time period for filtering',
    enum: ['today', 'week', 'month', 'year', 'all', 'custom'],
    required: false,
    example: 'month'
  })
  @IsOptional()
  @IsEnum(['today', 'week', 'month', 'year', 'all', 'custom'])
  period?: 'today' | 'week' | 'month' | 'year' | 'all' | 'custom';
}



export class DashboardMetricsDto {
  @ApiProperty({ description: 'Total number of orders in the period', example: 150 })
  totalOrders: number;

  @ApiProperty({ description: 'Total number of products in the catalog', example: 45 })
  totalProducts: number;

  @ApiProperty({ description: 'Total revenue generated in the period', example: 125000.50 })
  totalRevenue: number;

  @ApiProperty({ description: 'Total number of unique customers', example: 87 })
  totalCustomers: number;

  @ApiProperty({ description: 'Total traffic/visits to the store', example: 1250 })
  totalTraffic: number;

  @ApiProperty({ description: 'Orders growth percentage compared to previous period', example: 15.5 })
  ordersGrowth: number;

  @ApiProperty({ description: 'Revenue growth percentage compared to previous period', example: 22.3 })
  revenueGrowth: number;

  @ApiProperty({ description: 'Customers growth percentage compared to previous period', example: 18.7 })
  customersGrowth: number;

  @ApiProperty({ description: 'Traffic growth percentage compared to previous period', example: 12.4 })
  trafficGrowth: number;

  @ApiProperty({ description: 'Number of orders with pending status', example: 12 })
  pendingOrders: number;

  @ApiProperty({ description: 'Number of orders being processed', example: 25 })
  processingOrders: number;

  @ApiProperty({ description: 'Number of completed orders', example: 100 })
  completedOrders: number;

  @ApiProperty({ description: 'Number of cancelled orders', example: 13 })
  cancelledOrders: number;

  @ApiProperty({ description: 'Average order value', example: 833.34 })
  averageOrderValue: number;

  @ApiProperty({ description: 'Conversion rate (orders/traffic * 100)', example: 12.0 })
  conversionRate: number;

  @ApiProperty({ description: 'Total amount paid by customers', example: 110000.00 })
  totalPaid: number;

  @ApiProperty({ description: 'Total pending payment amount', example: 12000.50 })
  totalPending: number;

  @ApiProperty({ description: 'Total refunded amount', example: 3000.00 })
  totalRefunded: number;

  @ApiProperty({ description: 'Net revenue (paid - refunded)', example: 107000.00 })
  netRevenue: number;

  @ApiProperty({ description: 'Expected revenue from pending orders', example: 12000.50 })
  expectedRevenue: number;

  @ApiProperty({ description: 'Number of active products', example: 42 })
  activeProducts: number;

  @ApiProperty({ description: 'Number of out-of-stock products', example: 3 })
  outOfStockProducts: number;

  @ApiProperty({ description: 'Number of low-stock products (quantity < 10)', example: 8 })
  lowStockProducts: number;

  @ApiProperty({ description: 'Total product views/traffic', example: 1250 })
  totalProductViews: number;

  @ApiProperty({ description: 'Number of new customers in the period', example: 65 })
  newCustomers: number;

  @ApiProperty({ description: 'Number of returning customers', example: 22 })
  returningCustomers: number;

  @ApiProperty({ description: 'Number of guest orders (without registration)', example: 35 })
  guestOrders: number;

  @ApiProperty({ description: 'Average revenue per customer', example: 1436.78 })
  averageCustomerValue: number;

  @ApiProperty({ description: 'Traffic breakdown by source', type: [TrafficSourceMetric] })
  trafficBySource: TrafficSourceMetric[];

  @ApiProperty({ description: 'Top landing pages by visits', type: [LandingPageMetric] })
  topLandingPages: LandingPageMetric[];

  @ApiProperty({ description: 'Total amount settled to business', example: 95000.00 })
  totalSettled: number;

  @ApiProperty({ description: 'Amount pending settlement', example: 15000.50 })
  pendingSettlement: number;

  @ApiProperty({ description: 'Next settlement amount', example: 15000.50 })
  nextSettlementAmount: number;

  @ApiProperty({ description: 'Number of orders placed today', example: 5 })
  ordersToday: number;

  @ApiProperty({ description: 'Number of orders placed this week', example: 28 })
  ordersThisWeek: number;

  @ApiProperty({ description: 'Number of orders placed this month', example: 150 })
  ordersThisMonth: number;

  @ApiProperty({ description: 'Revenue generated today', example: 4500.00 })
  revenueToday: number;

  @ApiProperty({ description: 'Revenue generated this week', example: 23000.50 })
  revenueThisWeek: number;

  @ApiProperty({ description: 'Revenue generated this month', example: 125000.50 })
  revenueThisMonth: number;

  @ApiProperty({ description: 'Total number of reviews received', example: 234 })
  totalReviews: number;

  @ApiProperty({ description: 'Average rating from all reviews', example: 4.5 })
  averageRating: number;
}

export class CompleteDashboardDto {
  @ApiProperty({ description: 'Comprehensive dashboard metrics', type: DashboardMetricsDto })
  metrics: DashboardMetricsDto;

  @ApiProperty({ description: 'List of recent orders', type: [RecentOrderDto] })
  recentOrders: RecentOrderDto[];

  @ApiProperty({ description: 'Top-performing products', type: [TopProductDto] })
  topProducts: TopProductDto[];

  @ApiProperty({ description: 'Sales chart data over time', type: [SalesChartDataDto] })
  salesChart: SalesChartDataDto[];

  @ApiProperty({ description: 'Order status distribution', type: [OrderStatusDistributionDto] })
  orderStatusDistribution: OrderStatusDistributionDto[];

  @ApiProperty({ description: 'Payment method distribution', type: [PaymentMethodDistributionDto] })
  paymentMethodDistribution: PaymentMethodDistributionDto[];
}




