
const axios = require('axios');
const { v4: uuidv4 } = require('uuid');

const API_URL = 'http://localhost:4000/v1';

// Credentials from seed
const ADMIN = { email: 'admin@test.com', password: 'Admin@123' };
const MERCHANT = { email: 'merchant1@test.com', password: 'Test@123' };

let adminToken = '';
let merchantToken = '';
let merchantBusinessId = null;
let createdProductId = null;

async function login(email, password) {
    try {
        const res = await axios.post(`${API_URL}/users/login`, { email, password });
        return res.data.data.accessToken;
    } catch (e) {
        console.error(`Login failed for ${email}:`, e.message);
        throw e;
    }
}

async function runTests() {
    console.log('==========================================');
    console.log('  STARTING COMPREHENSIVE SYSTEM TEST');
    console.log('==========================================\n');

    try {
        // --- 1. AUTHENTICATION ---
        console.log('[1] AUTHENTICATION MODULE');
        console.log('Logging in Admin...');
        adminToken = await login(ADMIN.email, ADMIN.password);
        console.log('  ✓ Admin logged in');

        console.log('Logging in Merchant...');
        merchantToken = await login(MERCHANT.email, MERCHANT.password);
        console.log('  ✓ Merchant logged in');

        // --- 2. USERS MODULE ---
        console.log('\n[2] USERS MODULE');
        console.log('Fetching Merchant Profile...');
        const profileRes = await axios.get(`${API_URL}/users/profile`, {
            headers: { Authorization: `Bearer ${merchantToken}` }
        });
        console.log('  ✓ Profile fetched:', profileRes.data.data.user.email);

        // --- 3. BUSINESS MODULE ---
        console.log('\n[3] BUSINESS MODULE');
        console.log('Fetching Merchant Business...');
        try {
            // Try explicit "my-business" endpoint
            const myBizRes = await axios.get(`${API_URL}/business/my-business`, {
                headers: { Authorization: `Bearer ${merchantToken}` }
            });
            // Handle Global Interceptor wrapping
            const businessData = myBizRes.data.data || myBizRes.data;
            console.log('  ✓ Business found (via my-business):', businessData.businessName);
            merchantBusinessId = businessData.id;
        } catch (e) {
            console.log('  ! Failed to fetch my-business, trying Admin list...', e.message);
             try {
                const allBiz = await axios.get(`${API_URL}/business`, {
                    headers: { Authorization: `Bearer ${adminToken}` }
                });
                const myBiz = allBiz.data.find(b => b.userId === profileRes.data.data.user.id); // Adjust structure if needed
                 if (myBiz) {
                    console.log('  ✓ Business found (via Admin list):', myBiz.businessName);
                    merchantBusinessId = myBiz.id;
                } else {
                    console.warn('  ! No business found for merchant via Admin list');
                }
            } catch (ex) {
                 console.log('  ! Failed to fetch businesses via Admin:', ex.response?.status || ex.message);
            }
        }

        // --- 4. PRODUCT MODULE ---
        console.log('\n[4] PRODUCT MODULE');
        if (merchantBusinessId) {
            console.log('Creating Test Product...');
            try {
                // Get Categories first
                const catRes = await axios.get(`${API_URL}/categories`);
                const categoryName = catRes.data.data[0]?.name || 'Electronics';

                const productPayload = {
                    businessId: merchantBusinessId, // Required
                    name: `Auto Test Product ${Date.now()}`,
                    description: 'Generated by integration test',
                    price: 1500,
                    quantityInStock: 100,
                    category: categoryName,
                    hasVariation: false,
                    images: ['https://via.placeholder.com/150']
                };

                const prodRes = await axios.post(`${API_URL}/products`, productPayload, {
                    headers: { Authorization: `Bearer ${merchantToken}` }
                });
                createdProductId = prodRes.data.data.id;
                console.log('  ✓ Product Created:', prodRes.data.data.name);
            } catch (e) {
                console.error('  ✗ Product Creation Failed:', e.response?.data || e.message);
            }
        } else {
            console.log('  - Skipping Product Creation (No Business ID)');
        }

        console.log('Fetching Public Products...');
        const pubProdRes = await axios.get(`${API_URL}/products?limit=5`);
        console.log(`  ✓ Fetched ${pubProdRes.data.data.data ? pubProdRes.data.data.data.length : 0} products`);
        
        // --- 5. ORDER & CART MODULE ---
        console.log('\n[5] ORDER & CART MODULE');
        const targetProduct = pubProdRes.data.data.data ? pubProdRes.data.data.data[0] : null;
        if (targetProduct) {
             const sessionId = uuidv4();
             console.log('Adding item to Guest Cart...');
             await axios.post(`${API_URL}/cart/items`, {
                 productId: targetProduct.id,
                 quantity: 1
             }, { headers: { 'x-session-id': sessionId } });
             console.log('  ✓ Item added to cart');

             console.log('Creating Guest Order...');
             const orderPayload = {
                businessId: targetProduct.businessId,
                customerName: 'Auto Test',
                customerEmail: 'autotest@example.com',
                customerPhoneNumber: '08000000000',
                deliveryAddress: 'Test Address',
                state: 'Lagos',
                city: 'Ikeja',
                paymentMethod: 'card', 
                deliveryMethod: 'pickup'
            };
            const orderRes = await axios.post(`${API_URL}/orders/cart`, orderPayload, {
                headers: { 'x-session-id': sessionId }
            });
            console.log('  ✓ Order Created:', orderRes.data.data.orderReference);
        } else {
            console.warn('  ! No products available for Order test');
        }


        // --- 6. PRODUCT MUTATION (Update & Delete) ---
        console.log('\n[6] PRODUCT MUTATION (Update & Delete)');
        try {
            // Create a dedicated product for this test
            console.log('Creating Throwaway Product for Mutation...');
             const productPayload = {
                    businessId: merchantBusinessId, 
                    name: `Delete Me Product ${Date.now()}`,
                    description: 'To be deleted',
                    price: 1000,
                    quantityInStock: 10,
                    category: 'Electronics',
                    hasVariation: false,
                    images: ['https://via.placeholder.com/150']
            };
            const prodRes = await axios.post(`${API_URL}/products`, productPayload, {
                headers: { Authorization: `Bearer ${merchantToken}` }
            });
            const mutationProductId = prodRes.data.data.id;
            console.log(`  ✓ Product Created (ID: ${mutationProductId})`);

             console.log(`Updating product ${mutationProductId}...`);
             const updateRes = await axios.patch(`${API_URL}/products/${mutationProductId}`, 
                { price: 2000 }, 
                { headers: { Authorization: `Bearer ${merchantToken}` } }
             );
             console.log('  ✓ Product Updated:', updateRes.data.data.price === 2000 ? 'Price verified' : 'Price mismatch');

             console.log(`Deleting product ${mutationProductId}...`);
             await axios.delete(`${API_URL}/products/${mutationProductId}`, {
                headers: { Authorization: `Bearer ${merchantToken}` } 
             });
             console.log('  ✓ Product Deleted');
        } catch (e) {
            console.error('  ✗ Product Mutation Failed:', e.response?.data || e.message);
        }

        // --- 7. WALLET MODULE ---
        console.log('\n[7] WALLET MODULE (Finance)');
        try {
            console.log('Fetching Merchant Wallet...');
            const walletRes = await axios.get(`${API_URL}/wallets`, {
                headers: { Authorization: `Bearer ${merchantToken}` }
            });
            console.log('  ✓ Wallet fetched:', walletRes.data.wallet ? walletRes.data.wallet.walletReference : 'No wallet found');
        } catch (e) {
             if (e.response?.status === 404) {
                 console.log('  - No wallet exists for merchant (Expected if not generated)');
             } else {
                 console.error('  ✗ Wallet Fetch Failed:', e.message);
             }
        }

        // --- 8. ADMIN MODULE ---
        console.log('\n[8] ADMIN MODULE');
        try {
            console.log('Fetching Active Admins...');
            const adminRes = await axios.get(`${API_URL}/admin/active`, {
                headers: { Authorization: `Bearer ${adminToken}` }
            });
            console.log(`  ✓ Active Admins fetched: ${adminRes.data.data ? adminRes.data.data.length : 0}`);
        } catch (e) {
            console.error('  ✗ Admin Fetch Failed:', e.response?.data || e.message);
        }

        console.log('\n==========================================');
        console.log('  TEST COMPLETED SUCCESSFULLY');
        console.log('==========================================');

    } catch (err) {
        console.error('\n!!! CRITICAL TEST FAILURE !!!');
        console.error(err.message);
        if (err.response) {
            console.error('Status:', err.response.status);
            console.error('Data:', JSON.stringify(err.response.data, null, 2));
        }
    }
}

runTests();
