export enum NotificationChannels {
  SMS = 'SMS',
  EMAIL = 'EMAIL',
  WHATSAPP = 'WHATSAPP',
  CALL = 'CALL',
  PUSH_NOTIFICATION = 'PUSH_NOTIFICATION',
  IN_APP = 'IN_APP',
}

export enum NotificationType {
  VERIFY_PHONE = 'VERIFY_PHONE',
  VERIFY_EMAIL = 'VERIFY_EMAIL',
  ONBOARDING = 'ONBOARDING',
  AUTHENTICATION = 'AUTHENTICATION',

  REDEEM_REWARD = 'REDEEM_REWARD',

  RESET_PASSWORD = 'RESET_PASSWORD',
}
