import { MigrationInterface, QueryRunner } from "typeorm";

export class OrderRefctoring1762502502668 implements MigrationInterface {
    name = 'OrderRefctoring1762502502668'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."order_items_status_enum" AS ENUM('PENDING', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED', 'REFUNDED')`);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" SERIAL NOT NULL, "orderId" integer NOT NULL, "productId" integer NOT NULL, "productName" character varying NOT NULL, "productDescription" text, "price" numeric(10,2) NOT NULL, "quantity" integer NOT NULL DEFAULT '1', "subtotal" numeric(10,2) NOT NULL, "color" character varying, "size" character varying, "imageUrls" text, "status" "public"."order_items_status_enum" NOT NULL DEFAULT 'PENDING', "notes" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), "deletedAt" TIMESTAMP, CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f1d359a55923bb45b057fbdab0" ON "order_items" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_cdb99c05982d5191ac8465ac01" ON "order_items" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_f421c8981cca05954f98667134" ON "order_items" ("status") `);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "UQ_b44079e7599f6198a41c9dde63f"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "transactionRef"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "orderStatus"`);
        await queryRunner.query(`DROP TYPE "public"."orders_orderstatus_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "transactionStatus"`);
        await queryRunner.query(`DROP TYPE "public"."orders_transactionstatus_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "transactionMedium"`);
        await queryRunner.query(`DROP TYPE "public"."orders_transactionmedium_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "dateOfTransaction"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "productDetails"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "orderReference" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "UQ_a8bdfcfdf8520db858774ab453c" UNIQUE ("orderReference")`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "transactionReference" character varying`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "UQ_3b5b32cf9f908e4cf776a94d2a9" UNIQUE ("transactionReference")`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "city" character varying`);
        await queryRunner.query(`CREATE TYPE "public"."orders_status_enum" AS ENUM('PENDING', 'PROCESSING', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'RETURNED', 'REFUNDED')`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "status" "public"."orders_status_enum" NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`CREATE TYPE "public"."orders_paymentstatus_enum" AS ENUM('PENDING', 'INITIATED', 'PAID', 'PARTIALLY_PAID', 'FAILED', 'REFUNDED', 'PARTIALLY_REFUNDED', 'EXPIRED')`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "paymentStatus" "public"."orders_paymentstatus_enum" NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`CREATE TYPE "public"."orders_paymentmethod_enum" AS ENUM('MONNIFY', 'BANK_TRANSFER', 'CARD', 'WALLET', 'CASH_ON_DELIVERY', 'USSD')`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "paymentMethod" "public"."orders_paymentmethod_enum" NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."orders_deliverymethod_enum" AS ENUM('STANDARD', 'EXPRESS', 'PICKUP')`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "deliveryMethod" "public"."orders_deliverymethod_enum" NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "subtotal" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "shippingFee" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "tax" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "discount" numeric(10,2) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "total" numeric(10,2) NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "paymentDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "paymentDetails" json`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "estimatedDeliveryDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "deliveryDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "deliveryDetails" json`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "notes" text`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "isBusinessSettled" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "settlementReference" character varying`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "settlementDate" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "settlementDetails" json`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "userId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "orderItemId" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "imageUrls" text`);
        await queryRunner.query(`COMMENT ON COLUMN "reviews"."imageUrls" IS 'Array of image URLs'`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "isVisible" boolean NOT NULL DEFAULT true`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "isVerifiedPurchase" boolean NOT NULL DEFAULT false`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD "deletedAt" TIMESTAMP`);
        await queryRunner.query(`CREATE INDEX "IDX_151b79a83ba240b0cb31b2302d" ON "orders" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_778777c5d7d56ed1bbaa907b8e" ON "orders" ("businessId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1f4b9818a08b822a31493fdee9" ON "orders" ("createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_5025e0259ec0b1ffb5f0ea6685" ON "orders" ("userId", "businessId") `);
        await queryRunner.query(`CREATE INDEX "IDX_7ed5659e7139fc8bc039198cc1" ON "reviews" ("userId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d17ce9c119d29c7ec8c884044c" ON "reviews" ("businessId") `);
        await queryRunner.query(`CREATE INDEX "IDX_a6b3c434392f5d10ec17104366" ON "reviews" ("productId") `);
        await queryRunner.query(`CREATE INDEX "IDX_53a68dc905777554b7f702791f" ON "reviews" ("orderId") `);
        await queryRunner.query(`CREATE INDEX "IDX_1e6c554d615dd5a5bf0e11ee0e" ON "reviews" ("orderItemId") `);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_cdb99c05982d5191ac8465ac010" FOREIGN KEY ("productId") REFERENCES "products"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_7ed5659e7139fc8bc039198cc1f" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_53a68dc905777554b7f702791fa" FOREIGN KEY ("orderId") REFERENCES "orders"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_1e6c554d615dd5a5bf0e11ee0e9" FOREIGN KEY ("orderItemId") REFERENCES "order_items"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_1e6c554d615dd5a5bf0e11ee0e9"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_53a68dc905777554b7f702791fa"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_7ed5659e7139fc8bc039198cc1f"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_cdb99c05982d5191ac8465ac010"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_f1d359a55923bb45b057fbdab0d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1e6c554d615dd5a5bf0e11ee0e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_53a68dc905777554b7f702791f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a6b3c434392f5d10ec17104366"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d17ce9c119d29c7ec8c884044c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7ed5659e7139fc8bc039198cc1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5025e0259ec0b1ffb5f0ea6685"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f4b9818a08b822a31493fdee9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_778777c5d7d56ed1bbaa907b8e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_151b79a83ba240b0cb31b2302d"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "isVerifiedPurchase"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "isVisible"`);
        await queryRunner.query(`COMMENT ON COLUMN "reviews"."imageUrls" IS 'Array of image URLs'`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "imageUrls"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "orderItemId"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP COLUMN "userId"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "deletedAt"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "settlementDetails"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "settlementDate"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "settlementReference"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "isBusinessSettled"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "notes"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "deliveryDetails"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "deliveryDate"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "estimatedDeliveryDate"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "paymentDetails"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "paymentDate"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "total"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "discount"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "tax"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "shippingFee"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "subtotal"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "deliveryMethod"`);
        await queryRunner.query(`DROP TYPE "public"."orders_deliverymethod_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "paymentMethod"`);
        await queryRunner.query(`DROP TYPE "public"."orders_paymentmethod_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "paymentStatus"`);
        await queryRunner.query(`DROP TYPE "public"."orders_paymentstatus_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "status"`);
        await queryRunner.query(`DROP TYPE "public"."orders_status_enum"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "city"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "UQ_3b5b32cf9f908e4cf776a94d2a9"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "transactionReference"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP CONSTRAINT "UQ_a8bdfcfdf8520db858774ab453c"`);
        await queryRunner.query(`ALTER TABLE "orders" DROP COLUMN "orderReference"`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "productDetails" json NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "dateOfTransaction" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`CREATE TYPE "public"."orders_transactionmedium_enum" AS ENUM('web', 'mobile')`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "transactionMedium" "public"."orders_transactionmedium_enum" NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."orders_transactionstatus_enum" AS ENUM('pending', 'successful', 'failed', 'cancelled')`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "transactionStatus" "public"."orders_transactionstatus_enum" NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`CREATE TYPE "public"."orders_orderstatus_enum" AS ENUM('ordered', 'dispatched', 'delivered', 'returned')`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "orderStatus" "public"."orders_orderstatus_enum" NOT NULL DEFAULT 'ordered'`);
        await queryRunner.query(`ALTER TABLE "orders" ADD "transactionRef" character varying NOT NULL`);
        await queryRunner.query(`ALTER TABLE "orders" ADD CONSTRAINT "UQ_b44079e7599f6198a41c9dde63f" UNIQUE ("transactionRef")`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f421c8981cca05954f98667134"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cdb99c05982d5191ac8465ac01"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f1d359a55923bb45b057fbdab0"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP TYPE "public"."order_items_status_enum"`);
    }

}
